### PR TITLE
update beats master branch ref to main

### LINKED ISSUE #1758: Update beats functions
Beats just updated their primary branch from `master` to `main`, so the beats [code](https://github.com/elastic/detection-rules/blob/main/detection_rules/beats.py) will need to be updated accordingly

### PR DESCRIPTION
**Pull request by Mikaayenson**
## Issues
Resolves #1758 

## Summary
Updates any references of the beats `master` branch to point to `main`.

### CODE REVIEW

**Review by terrancedejesus — APPROVED** [review]
LGTM. Didn't find any other references to master that need changed.

**Comment by brokensound77** [comment]
Instead of renaming `etc/beats_schemas/main.json.gz`, can you just delete it and run `refresh_main_schema`

**Review by brokensound77 — APPROVED** [review]
Besides the one comment, LGTM 👍

**Comment by Mikaayenson** [comment]
Just a note, the beats archive has files that do not safe load. This appears to be already known given the try/except that prints them.

Here they are for future reference.

```

Downloading beats main
Downloaded 112.50 MB release.
Error loading beats-main/filebeat/scripts/fileset/config/config.yml
Error loading beats-main/filebeat/scripts/module/_meta/config.yml
Error loading beats-main/x-pack/filebeat/module/cisco/amp/config/config.yml
Error loading beats-main/x-pack/filebeat/module/google_workspace/admin/config/config.yml
Error loading beats-main/x-pack/filebeat/module/google_workspace/drive/config/config.yml
Error loading beats-main/x-pack/filebeat/module/google_workspace/groups/config/config.yml
Error loading beats-main/x-pack/filebeat/module/google_workspace/login/config/config.yml
Error loading beats-main/x-pack/filebeat/module/google_workspace/saml/config/config.yml
Error loading beats-main/x-pack/filebeat/module/google_workspace/user_accounts/config/config.yml
Error loading beats-main/x-pack/filebeat/module/mssql/log/config/config.yml
Error loading beats-main/x-pack/filebeat/module/mysqlenterprise/audit/config/config.yml
Error loading beats-main/x-pack/filebeat/module/oracle/database_audit/config/config.yml
Error loading beats-main/x-pack/filebeat/module/snyk/audit/config/config.yml
Error loading beats-main/x-pack/filebeat/module/snyk/vulnerabilities/config/config.yml
Error loading beats-main/x-pack/filebeat/module/sophos/xg/config/config.yml
Error loading beats-main/x-pack/filebeat/module/threatintel/abusemalware/config/config.yml
Error loading beats-main/x-pack/filebeat/module/threatintel/abuseurl/config/config.yml
Error loading beats-main/x-pack/filebeat/module/threatintel/anomali/config/config.yml
Error loading beats-main/x-pack/filebeat/module/threatintel/anomalithreatstream/config/config.yml
Error loading beats-main/x-pack/filebeat/module/threatintel/malwarebazaar/config/config.yml
Error loading beats-main/x-pack/filebeat/module/threatintel/misp/config/config.yml
Error loading beats-main/x-pack/filebeat/module/threatintel/otx/config/config.yml
Error loading beats-main/x-pack/filebeat/module/threatintel/threatq/config/config.yml
Saving etc/beats_schema/main.json

```

**Pull request merged**
