### PR TITLE
[Rule Tuning] Kubernetes - update min_stack for new rules

### PR DESCRIPTION
**Pull request by imays11**
## Issues

https://github.com/elastic/detection-rules/issues/2309 

## Link to rules
- https://github.com/elastic/detection-rules/blob/main/rules/integrations/kubernetes/discovery_denied_service_account_request.toml 
- https://github.com/elastic/detection-rules/blob/main/rules/integrations/kubernetes/initial_access_anonymous_request_authorized.toml 
- https://github.com/elastic/detection-rules/blob/main/rules/integrations/kubernetes/privilege_escalation_suspicious_assignment_of_controller_service_account.toml

## Description
 min_stack change to 8.4 with new required fields added to Kubernetes Integration

image

### CODE REVIEW

**Review by DefSecSentinel — APPROVED** [review]
LGTM

**Review by brokensound77 — APPROVED** [review]
Changes LGTM. Reminder that you will need to manually remove these from the 8.3 branch, since they've already been backported.

Will need to pay special attention to the version.lock. If it has not been locked with these in there, it will be straightforward, but if it has been, we will need to realign the version entry (cc: @terrancedejesus @Mikaayenson )

**Comment by terrancedejesus** [comment]
> Changes LGTM. Reminder that you will need to manually remove these from the 8.3 branch, since they've already been backported.
> 
> Will need to pay special attention to the version.lock. If it has not been locked with these in there, it will be straightforward, but if it has been, we will need to realign the version entry (cc: @terrancedejesus @Mikaayenson )

Confirmed it is not in the lock file as we have not locked yet so it should be a matter of removing the files from the branch.

**Comment by terrancedejesus** [comment]
@brokensound77 original PRs were started in draft, then to ready for review. The `backport: auto` label is not added to drafts and has to be manually added but never was. Therefore, these files only exist in main.

**Pull request merged**
