### PR TITLE
[Rule Tuning] Suspicious Inter-Process Communication via Outlook #3803

### PR DESCRIPTION
**Pull request by ar3diu**
## Issues

https://github.com/elastic/detection-rules/issues/3803
## Summary
Without a host grouping in the sequence of events, this rule triggers on events from different hosts which is not exactly the desired result.

### CODE REVIEW

**Comment by Samirbous** [comment]
> ## Issues
> #3803
> 
> ## Summary
> Without a host grouping in the sequence of events, this rule triggers on events from different hosts which is not exactly the desired result.

thanks for flagging this, adjusted you PR to use `process.Ext.effective_parent.entity_id` and `process.entity_id` (they are unique and more appropriate)

**Review by brokensound77 — APPROVED** [review]
LGTM

**Review by Samirbous — APPROVED** [review]

**Comment by brokensound77** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [cc150ef](https://github.com/elastic/detection-rules/commit/cc150efbde95db42a21c5bebd0dc74cc177c2089)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Thanks for the contribution @ar3diu - once you sign the CLA, @Samirbous can get this merged in 🎉

**Comment by ar3diu** [comment]
I already signed the contributor agreement, but I don't know why it's not updated...

Screenshot from the pdf downloaded:
image

**Comment by ar3diu** [comment]
@Mikaayenson should I close this one or...?
I don't get why the CLA test did not pass since I signed the agreement. Any tips on investigating that?

**Comment by ar3diu** [comment]
Hm, I noticed that too, but I don't get why the commit used that username. It probably has to do with my local instance of vs code. Anyway, I have signed the CLA now for both github (user)names.

**Comment by terrancedejesus** [comment]
Force merged this in since 2 approvals were checked and unit testing passed.
Reviewed commit history and diff to ensure delta did not contain any anomalies.

**Pull request merged**
