### PR TITLE
[WMI Incoming Lateral Movement] Adjust Query Exception for Nessus

### LINKED ISSUE #2773: [Rule Tuning] WMI Incoming Lateral Movement
## Link to rule
[lateral_movement_incoming_wmi.toml](https://github.com/elastic/detection-rules/blob/main/rules/windows/lateral_movement_incoming_wmi.toml)

## Description
The rule currently excludes `"C:\\windows\\TEMP\\nessus_*.TMP"`, but this does not encompass when Tenable (Nessus) sometimes passes the command with a fully-quoted command like this:

`C:\Windows\System32\cmd.exe /c "C:\Windows\System32\schtasks.exe /query /XML > C:\Windows\TEMP\nessus_X6I0QELU.TMP & ren C:\Windows\TEMP\nessus_X6I0QELU.TMP nessus_X6I0QELU.TXT"`

Based on the way this command is being passed, the three args come out as:

* `"C:\Windows\System32\cmd.exe"`
* `"/c"`
* `"C:\Windows\System32\schtasks.exe /query /XML > C:\Windows\TEMP\nessus_X6I0QELU.TMP & ren C:\Windows\TEMP\nessus_X6I0QELU.TMP nessus_X6I0QELU.TXT"`

As you can see, this does not match the exclusion `"C:\\windows\\TEMP\\nessus_*.TMP"` currently defined in the rule. I am proposing surrounding wildcards on the current exclusion, making it `"*C:\\windows\\TEMP\\nessus_*.TMP*"`. I have tested this in my environment, and it no longer falsely detects the activity from Tenable. 

## Example Data

```
{
  "is_partial": false,
  "is_running": false,
  "took": 242,
  "timed_out": false,
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "sequences": [
      {
        "join_keys": [
          "82186b27-29e1-4234-a98f-ef58248dbcdb"
        ],
        "events": [
          {
            "_index": ".ds-logs-endpoint.events.network-default-2023.03.10-000001",
            "_id": "UpoA44cBeN8Gnm9D2nVo",
            "_source": {
              "agent": {
                "id": "b891a62c-df71-4ab1-8b1c-50d979000000",
                "type": "endpoint",
                "version": "8.6.2"
              },
              "process": {
                "Ext": {
                  "ancestry": [
                    "Yjg5MWE2MmMtZGY3MS00YWIxLThiMWMtNTBkOTc5YWFhM2JjLTY0OC0xNjgyMzYwMDc3LjQ4NzQ3NDYwMA==",
                    "Yjg5MWE2MmMtZGY3MS00YWIxLThiMWMtNTBkOTc5YWFhM2JjLTk4MC0xNjgyMzYwMDc3LjM4MjI3ODEwMA=="
                  ],
                  "code_signature": [
                    {
                      "trusted": true,
                      "subject_name": "Microsoft Windows Publisher",
                      "exists": true,
                      "status": "trusted"
                    }
                  ]
                },
                "code_signature": {
                  "trusted": true,
                  "subject_name": "Microsoft Windows Publisher",
                  "exists": true,
                  "status": "trusted"
                },
                "name": "svchost.exe",
                "pid": 2324,
                "entity_id": "Yjg5MWE2MmMtZGY3MS00YWIxLThiMWMtNTBkOTc5YWFhM2JjLTIzMjQtMTY4MjM2MDA3OS4yNjUwNjYzMDA=",
                "executable": """C:\Windows\System32\svchost.exe"""
              },
              "destination": {
                "address": "192.168.0.10",
                "port": 63871,
                "ip": "192.168.0.10"
              },
              "source": {
                "address": "192.168.10.20",
                "port": 64489,
                "ip": "192.168.10.20"
              },
              "message": "Endpoint network event",
              "network": {
                "transport": "tcp",
                "type": "ipv4",
                "direction": "ingress"
              },
              "@timestamp": "2023-05-03T19:04:46.1756499Z",
              "ecs": {
                "version": "1.11.0"
              },
              "related": {
                "hosts": [
                  "HOST1"
                ],
                "ip": [
                  "192.168.0.10",
                  "fe80::2784:29d8:6343:c05a",
                  "127.0.0.1",
                  "::1",
                  "192.168.10.20"
                ],
                "user": [
                  "system"
                ],
                "mac": [
                  "00:15:5D:00:00:00",
                  "18:66:DA:00:00:01"
                ]
              },
              "data_stream": {
                "namespace": "default",
                "type": "logs",
                "dataset": "endpoint.events.network"
              },
              "elastic": {
                "agent": {
                  "id": "b891a62c-df71-4ab1-8b1c-50d979aaa3bc"
                }
              },
              "host": {
                "hostname": "HOST1",
                "os": {
                  "Ext": {
                    "variant": "Windows 10 Enterprise"
                  },
                  "kernel": "22H2 (10.0.19045.2846)",
                  "name": "Windows",
                  "family": "windows",
                  "type": "windows",
                  "version": "22H2 (10.0.19045.2846)",
                  "platform": "windows",
                  "full": "Windows 10 Enterprise 22H2 (10.0.19045.2846)"
                },
                "ip": [
                  "192.168.0.10",
                  "fe80::2784:29d8:6343:c05a",
                  "127.0.0.1",
                  "::1"
                ],
                "name": "HOST1",
                "id": "82186b27-29e1-4234-a98f-ef58248dbcdb",
                "mac": [
                  "00:15:5d:00:00:00",
                  "18:66:da:00:00:01"
                ],
                "architecture": "x86_64"
              },
              "event": {
                "agent_id_status": "verified",
                "sequence": 2867753,
                "ingested": "2023-05-03T19:04:56Z",
                "created": "2023-05-03T19:04:46.1756499Z",
                "kind": "event",
                "module": "endpoint",
                "action": "connection_accepted",
                "id": "N2P54sK1leAIxc0P++++Z77z",
                "category": [
                  "network"
                ],
                "type": [
                  "start"
                ],
                "dataset": "endpoint.events.network",
                "outcome": "success"
              },
              "user": {
                "domain": "NT AUTHORITY",
                "name": "system",
                "id": "S-1-5-18"
              }
            }
          },
          {
            "_index": ".ds-logs-endpoint.events.process-default-2023.03.10-000001",
            "_id": "WZoA44cBeN8Gnm9D2nVo",
            "_source": {
              "agent": {
                "id": "b891a62c-df71-4ab1-8b1c-50d979aaa3bc",
                "type": "endpoint",
                "version": "8.6.2"
              },
              "process": {
                "Ext": {
                  "ancestry": [
                    "Yjg5MWE2MmMtZGY3MS00YWIxLThiMWMtNTBkOTc5YWFhM2JjLTU0NjgtMTY4MjM2MDA4My4yMDMyODUzMDA=",
                    "Yjg5MWE2MmMtZGY3MS00YWIxLThiMWMtNTBkOTc5YWFhM2JjLTc1Ni0xNjgyMzYwMDc4LjI0Njc0MTAw",
                    "Yjg5MWE2MmMtZGY3MS00YWIxLThiMWMtNTBkOTc5YWFhM2JjLTY0OC0xNjgyMzYwMDc3LjQ4NzQ3NDYwMA==",
                    "Yjg5MWE2MmMtZGY3MS00YWIxLThiMWMtNTBkOTc5YWFhM2JjLTk4MC0xNjgyMzYwMDc3LjM4MjI3ODEwMA=="
                  ],
                  "code_signature": [
                    {
                      "trusted": true,
                      "subject_name": "Microsoft Windows",
                      "exists": true,
                      "status": "trusted"
                    }
                  ],
                  "session_info": {
                    "authentication_package": "Negotiate",
                    "relative_logon_time": 780609.2319164,
                    "id": 0
                  },
                  "relative_file_creation_time": 20534264.4952231,
                  "effective_parent": {
                    "name": "nessus-agent-module.exe",
                    "pid": 15492,
                    "entity_id": "Yjg5MWE2MmMtZGY3MS00YWIxLThiMWMtNTBkOTc5YWFhM2JjLTE1NDkyLTE2ODMxMjI2NzkuMTU4Nzk4NTAw",
                    "executable": """C:\Program Files\Tenable\Nessus Agent\nessus-agent-module.exe"""
                  },
                  "authentication_id": "0x3e7",
                  "relative_file_name_modify_time": 3112783.8680834,
                  "token": {
                    "integrity_level_name": "system",
                    "security_attributes": [
                      "TSA://ProcUnique"
                    ],
                    "elevation_level": "default"
                  }
                },
                "parent": {
                  "args": [
                    """C:\Windows\system32\wbem\wmiprvse.exe"""
                  ],
                  "name": "WmiPrvSE.exe",
                  "pid": 5468,
                  "args_count": 1,
                  "thread": {
                    "Ext": {
                      "call_stack_contains_unbacked": false
                    }
                  },
                  "entity_id": "Yjg5MWE2MmMtZGY3MS00YWIxLThiMWMtNTBkOTc5YWFhM2JjLTU0NjgtMTY4MjM2MDA4My4yMDMyODUzMDA=",
                  "command_line": """C:\Windows\system32\wbem\wmiprvse.exe""",
                  "executable": """C:\Windows\System32\wbem\WmiPrvSE.exe"""
                },
                "pid": 31232,
                "working_directory": """c:\windows\system32\spool\drivers\x64\3\""",
                "entity_id": "Yjg5MWE2MmMtZGY3MS00YWIxLThiMWMtNTBkOTc5YWFhM2JjLTMxMjMyLTE2ODMxNDA2ODYuOTMxOTE5MzAw",
                "executable": """C:\Windows\System32\cmd.exe""",
                "args": [
                  """C:\Windows\System32\cmd.exe""",
                  "/c",
                  """C:\Windows\System32\schtasks.exe /query /XML > C:\Windows\TEMP\nessus_X6I0QELU.TMP & ren C:\Windows\TEMP\nessus_X6I0QELU.TMP nessus_X6I0QELU.TXT"""
                ],
                "code_signature": {
                  "trusted": true,
                  "subject_name": "Microsoft Windows",
                  "exists": true,
                  "status": "trusted"
                },
                "pe": {
                  "imphash": "272245e2988e1e430500b852c4fb5e18",
                  "original_file_name": "Cmd.Exe"
                },
                "name": "cmd.exe",
                "args_count": 3,
                "command_line": "C:\\Windows\\System32\\cmd.exe /c \"C:\\Windows\\System32\\schtasks.exe /query /XML > C:\\Windows\\TEMP\\nessus_X6I0QELU.TMP & ren C:\\Windows\\TEMP\\nessus_X6I0QELU.TMP nessus_X6I0QELU.TXT\"",
                "hash": {
                  "sha1": "f1efb0fddc156e4c61c5f78a54700e4e7984d55d",
                  "sha256": "b99d61d874728edc0918ca0eb10eab93d381e7367e377406e65963366c874450",
                  "md5": "8a2122e8162dbef04694b9c3e0b6cdee"
                }
              },
              "@timestamp": "2023-05-03T19:04:46.9319193Z",
              "ecs": {
                "version": "1.11.0"
              },
              "related": {
                "hosts": [
                  "HOST1"
                ],
                "ip": [
                  "192.168.0.10",
                  "fe80::2784:29d8:6343:c05a",
                  "127.0.0.1",
                  "::1",
                  "192.168.10.20"
                ],
                "user": [
                  "system"
                ],
                "hash": [
                  "8A2122E8162DBEF04694B9C3E0B6CDEE",
                  "F1EFB0FDDC156E4C61C5F78A54700E4E7984D55D",
                  "B99D61D874728EDC0918CA0EB10EAB93D381E7367E377406E65963366C874450"
                ],
                "mac": [
                  "00:15:5D:00:00:00",
                  "18:66:DA:00:00:01"
                ]
              },
              "data_stream": {
                "namespace": "default",
                "type": "logs",
                "dataset": "endpoint.events.process"
              },
              "elastic": {
                "agent": {
                  "id": "b891a62c-df71-4ab1-8b1c-50d979aaa3bc"
                }
              },
              "host": {
                "hostname": "HOST1",
                "os": {
                  "Ext": {
                    "variant": "Windows 10 Enterprise"
                  },
                  "kernel": "22H2 (10.0.19045.2846)",
                  "name": "Windows",
                  "family": "windows",
                  "type": "windows",
                  "version": "22H2 (10.0.19045.2846)",
                  "platform": "windows",
                  "full": "Windows 10 Enterprise 22H2 (10.0.19045.2846)"
                },
                "ip": [
                  "192.168.0.10",
                  "fe80::2784:29d8:6343:c05a",
                  "127.0.0.1",
                  "::1",
                  "192.168.10.20"
                ],
                "name": "HOST1",
                "id": "82186b27-29e1-4234-a98f-ef58248dbcdb",
                "mac": [
                  "00:15:5d:00:00:00",
                  "18:66:da:00:00:01"
                ],
                "architecture": "x86_64"
              },
              "event": {
                "agent_id_status": "verified",
                "sequence": 2867773,
                "ingested": "2023-05-03T19:04:56Z",
                "created": "2023-05-03T19:04:46.9319193Z",
                "kind": "event",
                "module": "endpoint",
                "action": "start",
                "id": "N2P54sK1leAIxc0P++++Z78r",
                "category": [
                  "process"
                ],
                "type": [
                  "start"
                ],
                "dataset": "endpoint.events.process"
              },
              "message": "Endpoint process event",
              "user": {
                "domain": "NT AUTHORITY",
                "name": "system",
                "id": "S-1-5-18"
              }
            }
          }
        ]
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by MakoWish**
## Issues
* Closes #2773 

## Summary

The current exceptions to the query include a `process.args` value of `"C:\\windows\\TEMP\\nessus_*.TMP"`. However, some commands being run by Nessus have a fully quoted string including much more than the excepted argument like this:

`"C:\Windows\System32\schtasks.exe /query /XML > C:\Windows\TEMP\nessus_X6I0QELU.TMP & ren C:\Windows\TEMP\nessus_X6I0QELU.TMP nessus_X6I0QELU.TXT"`

Based on that full command line argument, the existing exception does not apply. This PR adjusts the above noted exception with leading and trailing wildcards. This has been tested and does correctly ignore the above argument as expected.

## Contributor checklist

[X] Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
[X] Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Review by w0rk3r — APPROVED** [review]
LGTM, thanks!

**Review by Aegrah — APPROVED** [review]
lgtm

**Comment by MakoWish** [comment]
Pinging @DefSecSentinel, @Samirbous, and @terrancedejesus. Can we get this merged?

**Comment by terrancedejesus** [comment]
> Pinging @DefSecSentinel, @Samirbous, and @terrancedejesus. Anything else needed to get this merged?

@MakoWish - Nothing else seems to be needed. Feel free to merge. Thank you again!

**Pull request merged**
