### PR TITLE
Create abuse_nslookup_with_dns_records.toml

### PR DESCRIPTION
**Pull request by prashanthpulisetti**
Title: Abuse Nslookup with DNS Records

Description: Red teamer's avoid IEX and Invoke-WebRequest in your PowerShell commands. Instead, host a text record with a payload to compromise hosts.

Reference : https://twitter.com/Alh4zr3d/status/1566489367232651264

### CODE REVIEW

**Comment by prashanthpulisetti** [comment]
I've signed contributor agreement, please check further.

**Review by w0rk3r — CHANGES_REQUESTED** [review]
Hey @prashanthpulisetti, thanks for the contribution. The rules should follow the format we use in our ruleset, examples can be found here: https://github.com/elastic/detection-rules/tree/main/rules/windows. More information about contributing to our repo can be found here: https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md

Thanks for your interest in contributing to our project!

**Comment by prashanthpulisetti** [comment]
Hi @w0rk3r , I've made changes, please review and let me know if any changes are needed.

**Comment by w0rk3r** [comment]
Hey @prashanthpulisetti, the TOML file still not following the structure we use in the repo:  https://github.com/elastic/detection-rules/tree/main/rules/windows

For example, here is a rule in the correct format:

image

Vs the format you use here:

image

The same applies to the other PRs

**Comment by w0rk3r** [comment]
Closing this one as it didn't receive any updates. Feel free to open another PR with the requested changes when you have time!

**Pull request closed without merging**
