### PR TITLE
[New Rule] Microsoft 365 Teams Custom Application Interaction Allowed

### LINKED ISSUE #567: [New Rule] O365 Teams Custom Application Interaction Allowed
## Description
Identifies when custom applications are allowed in Microsoft Teams. If an organization requires apps other than those available in the Teams app store, custom apps can be developed as app packages and uploaded. An adversary may abuse this behavior to establish persistence in an environment.

## Required Info

- **Eventing Sources:**
`filebeat-*`

- **Platforms**
`o365`

- **Target ECS Version:** `1.0.6`
- **New fields required in ECS for this?**
- **Related issues or PRs**

## Optional Info
- **References:**
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload

## Example Logic
```
event.dataset:o365.audit and event.provider:MicrosoftTeams and event.category:web and event.action:TeamsTenantSettingChanged and o365.audit.Name:"Allow sideloading and interaction of custom apps" and o365.audit.NewValue:True and event.outcome:success
```
## Screenshot 

image

### PR DESCRIPTION
**Pull request by bm11100**
## Issues
resolves #567 

## Summary

Identifies when custom applications are allowed in Microsoft Teams. If an organization requires applications other than those available in the Teams app store, custom applications can be developed as packages and uploaded. An adversary may abuse this behavior to establish persistence in an environment.

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by bm11100** [comment]
when #570 merges, the non-ecs-schema modification may no longer be needed. will confirm.

**Review by dstepanic17 — APPROVED** [review]
LGTM

**Comment by bm11100** [comment]
I still needed the `non-ecs-schema` even after #570 merged @brokensound77

**Comment by bm11100** [comment]
still pending whether we want `o365.audit.NewValue` in the non ecs schema

**Review by brokensound77 — APPROVED** [review]
Awesome!

**Pull request merged**
