### PR TITLE
Add ATT&CK subtechniques to the schema

### PR DESCRIPTION
**Pull request by rw-access**
## Issues
Part of #215 
Related/blocked by https://github.com/elastic/kibana/issues/75771
Related/blocked by https://github.com/elastic/kibana/pull/83511
Related to #614 

## Summary
Added ATT&CK subtechniques to the schema validation, and drop the field when downgrading from 7.10 to previous versions when the field wasn't available. I haven't added any CLI support yet. I'm not sure how we want to navigate that, especially when we allow multiple tactics in a single threat mapping.

### CODE REVIEW

**Review by brokensound77 — APPROVED** [review]
LGTM 👍

**Comment by brokensound77** [comment]
Looks like it merged in Kibana 🎉

**Review by devonakerr — APPROVED** [review]
LGTM

**Comment by rw-access** [comment]
@brokensound77 I think I assumed multiple tactics would also be fixed in the same PR. so I need to do some double checking before we merge

**Pull request merged**
