### PR TITLE
[New Rule] Azure Subscription Permission Elevation

### LINKED ISSUE #1630: [New Rule] Azure Subscription Permission Elevation
## Description

Identifies when a user has been elevated to manage all Azure Subscriptions. This setting could allow an attacker access to Azure subscriptions in your environment.

### Target indexes

`filebeat-*, logs-azure*`

### Platforms

Azure

### Query

```
(event.dataset:azure.activitylogs and 
azure.activitylogs.operation_name: "MICROSOFT.AUTHORIZATION/ELEVATEACCESS/ACTION" and 
event.outcome:(Success or success)) or
(event.dataset:azure.auditlogs and azure.auditlogs.operation_name: "Assigns the caller to user access admin" and 
event.outcome:(Success or success))
```

### **False Positives**
- 
- 

### MITRE

| Tactic | Technique ID | Technique Name | Sub-Technique Name |
| ------ | ------------ | ------------------ | --------------------- |
|            |                       |                                |                                      |
|            |                       |                                |                                      |

### References

-  https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/security-operations-privileged-accounts#assignment-and-elevation
- https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftauthorization

### PR DESCRIPTION
**Pull request by austinsonger**
## Issues

Resolves #1630

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by w0rk3r** [comment]
@austinsonger can you provide an event for this one?

**Comment by austinsonger** [comment]
@w0rk3r  Yeah I will this is still in draft form, so when I make this ready it will include that. Still in testing.

**Comment by w0rk3r** [comment]
Hey @austinsonger, let's reserve draft PRs for rules that need collaboration, you can open new PRs when the rules are ready for review and provide sample data for us to validate them.

**Comment by austinsonger** [comment]
@w0rk3r Can you reopen this, so I can close it because I can reopen it. Because if you close it, I can't reopen the Pull Request.

**Pull request closed without merging**
