### PR TITLE
[Rule Tuning] Untrusted Driver Loaded

### PR DESCRIPTION
**Pull request by w0rk3r**
## Summary

Changes the event.category to `driver`, in order to make the rule work with the stack EQL. 

image

### CODE REVIEW

**Review by terrancedejesus — APPROVED** [review]
Looks good.

**Comment by Aegrah** [comment]
It seems like the tagging might be off in this rule, could be good to change that as well. 

`tags = ["Elastic", "Host", "macOS", "Threat Detection", "Defense Evasion"]`

Unless it's a macOS rule as well, but I doubt it. Other than that, LGTM.

**Comment by w0rk3r** [comment]
Nice catch @Aegrah, saw it and I'm fixing it on the investigation guide PR

**Review by Aegrah — APPROVED** [review]
Other than the macOS tag, LGTM

**Review by Samirbous — APPROVED** [review]

**Pull request merged**
