### PR TITLE
[Rule Tuning] Update rules for new Fleet integrations

### LINKED ISSUE #719: [Rule Tuning] Update rules to account for new Fleet Integrations
## Description
With the new Fleet integrations, we will need to update all rules that now have an integration with the Agent.

See this meta issue https://github.com/elastic/detection-rules/issues/255 

This is likely to include Azure, M365, and GCP/Google Workspace. 

## Example for Azure
```
index = ["filebeat-*", "logs-azure.*"]
```

### PR DESCRIPTION
**Pull request by bm11100**
## Issues
resolves #719 

## Summary
With the new Fleet integrations, we will need to update all rules that now have an integration with the Agent.

This PR updates cloud rules with the new indices. It may also be used to account for syntax changes in the module/data streams. 

## Updates:

- `logs-azure*` index was added to Azure rules to account for new Fleet integration
- `logs-gcp*` index was added in preparation of GCP Fleet integration
- `gcp.audit` syntax was added to event.dataset to account for the Filebeat module rename in https://github.com/elastic/beats/pull/22214
- `logs-google_workspace*` index was added in preparation of Google Workspace Fleet integration
- `google_workspace.admin` syntax was added to event.dataset to account for the updated module name https://github.com/elastic/beats/issues/22427
- `logs-o365*` index added to all O365 rules to account for Fleet integration (this still needs to be updated to M365 in the future)
- updated Azure rules event.dataset to `Success or success` as we noticed an older Filebeat module uppercased the S but the Agent has it lowercase (other cloud rules are all lowercase)

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Review by rw-access — APPROVED** [review]

**Review by brokensound77 — APPROVED** [review]
awesome, LGTM 👍 

Can you also add a summary of what all was changed in this PR to the description too 🙏

**Comment by bm11100** [comment]
@jamiehynds can you confirm all of the changes are correct and if there are anymore updates in 7.11 we need to account for from the Integrations perspective?

**Comment by jamiehynds** [comment]
@bm11100 changes look good, and we have some additional modules that were migrated in 7.11 too. You can see them here: https://github.com/elastic/security-team/issues/367

Defender ATP will not make it for 7.11, but the other items that are unticked are expected to make it in. 

Packetbeat has also been migrated to a package. Presume this has an impact on some rules too?

**Comment by bm11100** [comment]
Spoke to @jamiehynds. Packetbeat made it in for 7.11, but there are no packages in the Agent that are using it yet.

**Pull request merged**
