### PR TITLE
[Suspicious PowerShell Engine ImageLoad] Add Ssms.exe to query exceptions

### LINKED ISSUE #2830: [Rule Tuning] Suspicious PowerShell Engine ImageLoad
## Link to rule
[execution_suspicious_powershell_imgload.toml](https://github.com/elastic/detection-rules/blob/main/rules/windows/execution_suspicious_powershell_imgload.toml)

## Description
Launching SQL Server Management Studio loads "System.Management.Automation.dll". An exception should be added to the query for a process name of `Ssms.exe`. 

## Example Data
```
{
  "agent": {
    "id": "c6d3cbb2-df12-abcd-9876-123456789abc",
    "type": "endpoint",
    "version": "8.6.2"
  },
  "process": {
    "Ext": {
      "ancestry": [],
      "code_signature": []
    },
    "pid": 38468
  },
  "@timestamp": "2023-05-26T18:44:00.0761777Z",
  "ecs": {
    "version": "1.11.0"
  },
  "related": {
    "hosts": [
      "Computer1"
    ],
    "ip": [
      "10.10.10.10"
    ],
    "mac": [
      "AB:CD:EF:12:34:56"
    ]
  },
  "dll": {
    "Ext": {
      "code_signature": [],
      "relative_file_creation_time": 6118425.7541429,
      "relative_file_name_modify_time": 6118425.6515904
    },
    "path": "C:\\Windows\\assembly\\NativeImages_v4.0.30319_64\\System.Manaa57fc8cc#\\326df18eb92a3af66ffa73ef7919bbee\\System.Management.Automation.ni.dll",
    "code_signature": {
      "exists": false
    },
    "pe": {
      "file_version": "10.0.19041.2673",
      "imphash": "d41d8cd98f00b204e9800998ecf8427e",
      "original_file_name": "System.Management.Automation.dll"
    },
    "name": "System.Management.Automation.ni.dll",
    "hash": {
      "sha1": "86b9d73e948b427ca94ec1091f3492de1bdc84b0",
      "sha256": "333e6206f944a110368a241d764e12555755d8cb0aea17bb5cc051ba46e67ed7",
      "md5": "7ff5f3e25b10313043271639bf2b27e7"
    }
  },
  "data_stream": {
    "namespace": "default",
    "type": "logs",
    "dataset": "endpoint.events.library"
  },
  "elastic": {
    "agent": {
      "id": "c6d3cbb2-df12-abcd-9876-123456789abc"
    }
  },
  "host": {
    "hostname": "Computer1",
    "os": {
      "Ext": {
        "variant": "Windows 10 Enterprise"
      },
      "kernel": "22H2 (10.0.19045.2965)",
      "name": "Windows",
      "family": "windows",
      "type": "windows",
      "version": "22H2 (10.0.19045.2965)",
      "platform": "windows",
      "full": "Windows 10 Enterprise 22H2 (10.0.19045.2965)"
    },
    "ip": [
      "10.10.10.10"
    ],
    "name": "Computer1",
    "id": "38666e42-079a-abcd-1234-987654321fed",
    "mac": [
      "AB:CD:EF:12:34:56"
    ],
    "architecture": "x86_64"
  },
  "event": {
    "agent_id_status": "verified",
    "sequence": 1770395,
    "ingested": "2023-05-26T18:44:18Z",
    "created": "2023-05-26T18:44:00.0761777Z",
    "kind": "event",
    "module": "endpoint",
    "action": "load",
    "id": "N4sbXMx4bDHAQyrL++++DEYt",
    "category": [
      "library"
    ],
    "type": [
      "start"
    ],
    "dataset": "endpoint.events.library"
  },
  "message": "Endpoint DLL load event"
}
```

### PR DESCRIPTION
**Pull request by MakoWish**
## Issues
- Closes #2830 

## Summary
Launching SQL Server Management Studio loads "System.Management.Automation.dll". Adding an exception to the query for a process name of `Ssms.exe`. 

## Contributor checklist

- [X] Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- [X] Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Review by w0rk3r — APPROVED** [review]
LGTM, thanks!
Can you bump the updated_date so we can merge it?

**Comment by MakoWish** [comment]
D'oh! Done.

**Comment by MakoWish** [comment]
If no other concerns, can someone get this merged? 

Understanding merges only occur after approvals, what would be required to get permissions to perform merges?

**Comment by w0rk3r** [comment]
Hey, I'm going to merge it. 

Currently, permissions to merge are restricted to our team members. But don't worry, before releasing, we double-check for what needs to be merged. But feel free to ping me in any PR for updates or remind me to merge ;)

**Pull request merged**
