### PR TITLE
[Rule Tuning] Possible Consent Grant Attack via Azure-Registered Application

### LINKED ISSUE #402: [Rule Tuning] Possible Consent Grant Attack via Azure-Registered Application
## Description

A `Consent to application.` event is logged in O365 logs when an administrator or individual user grants consent to an application. Expand this existing rule to incorporate the relevant O365 index patterns.

The query below should do the trick. I need to simulate this activity before opening a PR to tune the rule.

```
event.dataset:(o365.audit or azure.activitylogs or azure.auditlogs) and (o365.audit.Operation:"Consent to application." or azure.activitylogs.operation_name:"Consent to application" or azure.auditlogs.operation_name:"Consent to application") and event.outcome:success
```

### PR DESCRIPTION
**Pull request by threat-punter**
## Issues

Resolves #402 

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by threat-punter** [comment]
I see the error below when linting the rule

```
kql.errors.KqlParseError: Error at line:1,column:196
Unknown field
event.dataset:(azure.activitylogs or azure.auditlogs or o365.audit) and ( azure.activitylogs.operation_name:"Consent to application" or azure.auditlogs.operation_name:"Consent to application" or o365.audit.Operation:"Consent to application" ) and event.outcome:success
                                                                                                                                                                                                   ^^^^^^^^^^^^^^^^^^^^
```

I verified that the field `o365.audit.Operation` exists, as per this comment https://github.com/elastic/detection-rules/issues/402#issuecomment-724982150

@brokensound77 do we need to update the schema for the O365 Filebeat module?

**Comment by bm11100** [comment]
> I see the error below when linting the rule
> 
> ```
> kql.errors.KqlParseError: Error at line:1,column:196
> Unknown field
> event.dataset:(azure.activitylogs or azure.auditlogs or o365.audit) and ( azure.activitylogs.operation_name:"Consent to application" or azure.auditlogs.operation_name:"Consent to application" or o365.audit.Operation:"Consent to application" ) and event.outcome:success
>                                                                                                                                                                                                    ^^^^^^^^^^^^^^^^^^^^
> ```
> 
> I verified that the field `o365.audit.Operation` exists, as per this comment [#402 (comment)](https://github.com/elastic/detection-rules/issues/402#issuecomment-724982150)
> 
> @brokensound77 do we need to update the schema for the O365 Filebeat module?

may need to add it to the `non-ecs-schema.json` file?

**Comment by brokensound77** [comment]
>I see the error below when linting the rule

>kql.errors.KqlParseError: Error at line:1,column:196
Unknown field
event.dataset:(azure.activitylogs or azure.auditlogs or o365.audit) and ( azure.activitylogs.operation_name:"Consent to application" or azure.auditlogs.operation_name:"Consent to application" or o365.audit.Operation:"Consent to application" ) and event.outcome:success
                                                                                                                                                                                                   ^^^^^^^^^^^^^^^^^^^^
>I verified that the field o365.audit.Operation exists, as per this comment #402 (comment)

>@brokensound77 do we need to update the schema for the O365 Filebeat module?

@threat-punter, looks like it is in 7.10.0, so once #570 merges, this should pass

**Comment by threat-punter** [comment]
Perfect

**Comment by threat-punter** [comment]
Our tests are still failing for this one.

**Review by bm11100 — APPROVED** [review]

**Review by brokensound77 — APPROVED** [review]
bump `updated_at` and LGTM 👍

**Pull request merged**
