### PR TITLE
[Tuning] event.action and event.type change

### PR DESCRIPTION
**Pull request by Aegrah**
## Summary
This PR changes the sequence of the `event.action` and `event.type`, to increase query performance.

### CODE REVIEW

**Comment by terrancedejesus** [comment]
@Aegrah I noticed you mentioned this is related to performance increases, but do we have benchmarks or testing to confirm these changes will increase performance?

**Comment by w0rk3r** [comment]
@terrancedejesus, this relates to our discussion while reviewing one of Ruben's PRs in EAH. Filtering for `event.type` first reduces the size of the dataset, and filtering after `event.action` and then `event.type` doesn't make sense as it will always have the same value.

**Comment by Aegrah** [comment]
@terrancedejesus exactly what @w0rk3r said. We discussed whether we would remove the `event.type == "start"` from the queries entirely; but concluded that reducing the query sample to all `start` events before continuing the rest of the query would likely see benefits, and having the `event.type == "start"` in the query does provide readibility.

**Review by w0rk3r — APPROVED** [review]
🙇🏼‍♂️

**Review by terrancedejesus — APPROVED** [review]
@Aegrah @w0rk3r - Thank you for taking the time to remind me of our conversation 😅

**Pull request merged**
