### PR TITLE
[Rule Tuning] Updating rules to query both versions of certain unsupervised ML jobs

### PR DESCRIPTION
**Pull request by ajosh0504**
## Issues
Related to [this](https://github.com/elastic/mechagodzilla/issues/150) issue.

## Summary
ML rules can now query multiple anomaly indices from multiple jobs, such as when we have two versions of a job with older and newer data feed queries (the 2020 jobs use new fields like event.category in order to work on Linux and Windows events from many different sources). 14 ML rules have been updated in this PR to query results from the two versions of their underlying ML jobs.

### CODE REVIEW

**Comment by rw-access** [comment]
@ajosh0504 what is the first stack release where these jobs are available? Are they new 7.13 or 7.14 jobs?

**Comment by randomuserid** [comment]
> @ajosh0504 what is the first stack release where these jobs are available? Are they new 7.13 or 7.14 jobs?

The new modules, containing the new jobs, were actually released prior to 7.13. These new multi-index rule types were not merged until very recently, at the tail end of the 7.13 release.

**Review by randomuserid — APPROVED** [review]
Looks good, I see all jobs from the v2 modules added.

**Comment by randomuserid** [comment]
@ryland does this look OK to you

**Review by rylnd — COMMENTED** [review]
Code changes look good! I defer to @rw-access for verification of TOML/output validity as I haven't been in this repo much lately 👍. Happy to make another pass with some review instructions, though!

Edit: also, it's @rylnd 😉

**Comment by ajosh0504** [comment]
@rw-access Can I get a 👍 on this?

**Comment by rw-access** [comment]
The only downside is that backports to pre 7.13 via kibana-upload don't work anymore because it's a breaking change in the rule.

Not necessarily a bad thing, but worth noting. @brokensound77 any hesitations with that in mind?

**Comment by randomuserid** [comment]
> Also @randomuserid @ajosh0504 do you want these changes to target 7.13 or 7.14 stacks?

I think we could target both since the new and improved rules work in 7.13 and later releases. Or if that's not feasible we could just make them a 7.14 & later feature

**Review by rw-access — APPROVED** [review]

**Pull request merged**
