### PR TITLE
[Unusual File Creation ADS] Add MS Office Applications to Query Exceptions

### LINKED ISSUE #2835: [Rule Tuning] Unusual File Creation - Alternate Data Stream
## Link to rule
[defense_evasion_unusual_ads_file_creation.toml](https://github.com/elastic/detection-rules/blob/main/rules/windows/defense_evasion_unusual_ads_file_creation.toml)

## Description
Additional MS Office applications have been found to trigger this rule since the last inclusion of Outlook.exe. I would like to also add EXCEL.EXE, POWERPNT.EXE, and WINWORD.EXE to the query exceptions.

### PR DESCRIPTION
**Pull request by MakoWish**
## Issues
- Closes #2835 

## Summary
Additional MS Office applications have been found to falsely trigger this rule since the recent addition of `OUTLOOK.EXE` to the query exceptions in #2814. This PR adds `EXCEL.EXE`, `POWERPNT.EXE`, and `WINWORD.EXE` to the query exceptions. 

## Contributor checklist

- [X] Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- [X] Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Review by w0rk3r — APPROVED** [review]

**Comment by w0rk3r** [comment]
Nice!

**Comment by MakoWish** [comment]
@terrancedejesus, 

Everything look okay with this one?

**Comment by MakoWish** [comment]
Pinging @terrancedejesus

**Review by imays11 — APPROVED** [review]
Looks good!

**Comment by MakoWish** [comment]
I can't merge, so would appreciate if someone could.

**Pull request merged**
