### PR TITLE
[FR] Normalize yml ext to yaml

### LINKED ISSUE #3622: [FR] normalize use of yaml extension (vs yml)
There are multiple config files under `etc/` that use the 2 different yaml extensions. This should be normalized and merged to main. 

Then in a second PR targeting [DAC-feature](https://github.com/elastic/detection-rules/blob/DAC-feature/detection_rules/config.py#L198), the changes should be merged back and then that branch updated as well so that the config parser and dataclasses also use a standardized extension

### PR DESCRIPTION
**Pull request by Mikaayenson**
## Issues

Related to #3622 

## Summary

Normalizes yml etc/* files to yaml. 
- packages.yml --> packages.yaml
- rule-mapping.yml --> rule-mapping.yaml

### CODE REVIEW

**Comment by shashank-elastic** [comment]
Locally Ran the Test on the dev branch.

Modified extensions and tests look good 🟢 

```
tests/test_all_rules.py::TestValidRules::test_all_rule_queries_optimized PASSED                                                                                                                                                          [ 42%]
tests/test_all_rules.py::TestValidRules::test_bbr_validation PASSED                                                                                                                                                                      [ 43%]
tests/test_all_rules.py::TestValidRules::test_duplicate_file_names PASSED                                                                                                                                                                [ 44%]
tests/test_all_rules.py::TestValidRules::test_file_names PASSED                                                                                                                                                                          [ 44%]
tests/test_all_rules.py::TestValidRules::test_max_signals_note PASSED                                                                                                                                                                    [ 45%]
tests/test_all_rules.py::TestValidRules::test_production_rules_have_rta PASSED                                                                                                                                                           [ 46%]
tests/test_all_rules.py::TestValidRules::test_rule_type_changes PASSED                                                                                                                                                                   [ 46%]
tests/test_all_rules.py::TestValidRules::test_schema_and_dupes PASSED                                                                                                                                                                    [ 47%]
tests/test_all_rules.py::TestThreatMappings::test_duplicated_tactics PASSED                                                                                                                                                              [ 48%]
tests/test_all_rules.py::TestThreatMappings::test_tactic_to_technique_correlations PASSED                                                                                                                                                [ 48%]
tests/test_all_rules.py::TestThreatMappings::test_technique_deprecations PASSED                                                                                                                                                          [ 49%]
tests/test_all_rules.py::TestRuleTags::test_casing_and_spacing PASSED                                                                                                                                                                    [ 50%]
tests/test_all_rules.py::TestRuleTags::test_investigation_guide_tag SKIPPED (Skipping until all Investigation Guides follow the proper format.)                                                                                          [ 51%]
tests/test_all_rules.py::TestRuleTags::test_ml_rule_type_tags PASSED                                                                                                                                                                     [ 51%]
tests/test_all_rules.py::TestRuleTags::test_no_duplicate_tags PASSED                                                                                                                                                                     [ 52%]
tests/test_all_rules.py::TestRuleTags::test_os_tags PASSED                                                                                                                                                                               [ 53%]
tests/test_all_rules.py::TestRuleTags::test_primary_tactic_as_tag PASSED                                                                                                                                                                 [ 53%]
tests/test_all_rules.py::TestRuleTags::test_required_tags PASSED                                                                                                                                                                         [ 54%]
tests/test_all_rules.py::TestRuleTags::test_tag_prefix PASSED                                                                                                                                                                            [ 55%]
tests/test_all_rules.py::TestRuleTimelines::test_timeline_has_title PASSED                                                                                                                                                               [ 55%]
tests/test_all_rules.py::TestRuleFiles::test_bbr_in_correct_dir PASSED                                                                                                                                                                   [ 56%]
tests/test_all_rules.py::TestRuleFiles::test_non_bbr_in_correct_dir PASSED                                                                                                                                                               [ 57%]
tests/test_all_rules.py::TestRuleFiles::test_rule_file_name_tactic PASSED                                                                                                                                                                [ 57%]
tests/test_all_rules.py::TestRuleMetadata::test_deprecated_rules PASSED                                                                                                                                                                  [ 58%]
tests/test_all_rules.py::TestRuleMetadata::test_event_dataset PASSED                                                                                                                                                                     [ 59%]
tests/test_all_rules.py::TestRuleMetadata::test_integration_tag PASSED                                                                                                                                                                   [ 60%]
tests/test_all_rules.py::TestRuleMetadata::test_invalid_queries PASSED                                                                                                                                                                   [ 60%]
tests/test_all_rules.py::TestRuleMetadata::test_updated_date_newer_than_creation PASSED                                                                                                                                                  [ 61%]
tests/test_all_rules.py::TestIntegrationRules::test_all_min_stack_rules_have_comment PASSED                                                                                                                                              [ 62%]
tests/test_all_rules.py::TestIntegrationRules::test_integration_guide SKIPPED (8.3+ Stacks Have Related Integrations Feature)                                                                                                            [ 62%]
tests/test_all_rules.py::TestIntegrationRules::test_ml_integration_jobs_exist PASSED                                                                                                                                                     [ 63%]
tests/test_all_rules.py::TestIntegrationRules::test_rule_demotions PASSED                                                                                                                                                                [ 64%]
tests/test_all_rules.py::TestRuleTiming::test_eql_interval_to_maxspan PASSED                                                                                                                                                             [ 64%]
tests/test_all_rules.py::TestRuleTiming::test_eql_lookback PASSED                                                                                                                                                                        [ 65%]
tests/test_all_rules.py::TestRuleTiming::test_event_override PASSED                                                                                                                                                                      [ 66%]
tests/test_all_rules.py::TestRuleTiming::test_required_lookback PASSED                                                                                                                                                                   [ 66%]
tests/test_all_rules.py::TestLicense::test_elastic_license_only_v2 PASSED                                                                                                                                                                [ 67%]
tests/test_all_rules.py::TestIncompatibleFields::test_rule_backports_for_restricted_fields PASSED                                                                                                                                        [ 68%]
tests/test_all_rules.py::TestBuildTimeFields::test_build_fields_min_stack PASSED                                                                                                                                                         [ 68%]
tests/test_all_rules.py::TestRiskScoreMismatch::test_rule_risk_score_severity_mismatch PASSED                                                                                                                                            [ 69%]
tests/test_all_rules.py::TestNoteMarkdownPlugins::test_if_plugins_explicitly_defined PASSED                                                                                                                                              [ 70%]
tests/test_all_rules.py::TestNoteMarkdownPlugins::test_note_has_osquery_warning PASSED                                                                                                                                                   [ 71%]
tests/test_all_rules.py::TestNoteMarkdownPlugins::test_plugin_placeholders_match_entries PASSED                                                                                                                                          [ 71%]
tests/test_all_rules.py::TestAlertSuppression::test_group_field_in_schemas PASSED    
tests/test_mappings.py::TestMappings::test_false_positives PASSED                                                                                                                                                                        [ 75%]
tests/test_mappings.py::TestMappings::test_true_positives PASSED                                                                                                                                                                         [ 76%]
tests/test_mappings.py::TestRTAs::test_rtas_with_triggered_rules_have_uuid PASSED    
tests/test_packages.py::TestPackages::test_package_loader_default_configs PASSED                                                                                                                                                         [ 77%]
tests/test_packages.py::TestPackages::test_package_loader_production_config PASSED                                                                                                                                                       [ 78%]
tests/test_packages.py::TestPackages::test_package_summary PASSED                                                                                                                                                                        [ 79%]
tests/test_packages.py::TestPackages::test_rule_versioning PASSED                                                                                                                                                                        [ 80%]
tests/test_packages.py::TestRegistryPackage::test_registry_package_config PASSED 
````

**Review by shashank-elastic — APPROVED** [review]

**Review by traut — APPROVED** [review]
👍

**Comment by eric-forte-elastic** [comment]
Should we also update the .yml in `get-target-branches.yml`  and `beats.py` or would that be for a different PR? 
image

**Comment by Mikaayenson** [comment]
> Should we also update the .yml in `get-target-branches.yml` or would that be for a different PR? 

I can update it for consistency. It's a file generated so we dont actually track it, but its a good seperation of GitHub workflow yml files for detection-rules yaml files.

**Review by eric-forte-elastic — APPROVED** [review]
:green_circle: Manual review, looks good to me! :+1:

**Pull request merged**
