### PR TITLE
Update ProblemChild detection rules with High and Low probability

### PR DESCRIPTION
**Pull request by sodhikirti07**
# Pull Request

*Issue link(s)*:

- https://github.com/elastic/security-ml/issues/424
## Summary - What I changed

- Updated the ProblemChild rule to include low probability detections: `defense_evasion_ml_suspicious_windows_event.toml` -> `defense_evasion_ml_suspicious_windows_event_low_probability.toml`.
- Adjusted the `risk_score` of `defense_evasion_ml_suspicious_windows_event_high_probability.toml` from 21 (low) to 73 (high).
## Checklist

- [x] Added a label for the type of pr: `bug`, `enhancement`, `schema`, `Rule: New`, `Rule: Deprecation`, `Rule: Tuning`, `Hunt: New`, or `Hunt: Tuning` so guidelines can be generated
- [ ] Added the `meta:rapid-merge` label if planning to merge within 24 hours
- [ ] Secret and sensitive material has been managed correctly
- [ ] Automated testing was updated or added to match the most common scenarios
- [ ] Documentation and comments were added for features that require explanation

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by sodhikirti07** [comment]
@shashank-elastic Please let me know if this PR requires anything else.

**Comment by shashank-elastic** [comment]
There are Unit Test failures which needs to be investigated, Also a quick check is this dependent on the latest Problem Child version release that went out yesterday @sodhikirti07

**Comment by jmcarlock** [comment]
@shashank-elastic it might be dependent on the new version of ProblemChild from yesterday, as the prior version was not passing the tests.

**Comment by sodhikirti07** [comment]
> There are Unit Test failures which needs to be investigated, Also a quick check is this dependent on the latest Problem Child version release that went out yesterday @sodhikirti07

Yesterday's PR for ProblemChild reintroduced the files for custom fields, which caused the detection-rules tests to fail. However, it didn't modify anything else, such as the min_kibana_version, etc. I'm not sure what's causing the unit test failures.

**Comment by shashank-elastic** [comment]
@sodhikirti07 Will debug the Unit test failures, juggling between artifact releases so this might take some time.

**Comment by shashank-elastic** [comment]
Unit Tests should pass as there was a fix made to the issue yesterday https://github.com/elastic/detection-rules/pull/4003

**Review by shashank-elastic — APPROVED** [review]
Unit Test Pass with the recent Fix.

The tuning of severity and the query for the problemchild rules look good.

**Review by jmcarlock — APPROVED** [review]

**Pull request merged**
