### PR TITLE
[Bug] Fix Kibana connector to work with 7.10

### LINKED ISSUE #403: [Bug] Auth for Kibana Connector fails with 7.10
**Describe the bug**
The auth data structure was changed in Kibana in elastic/kibana/pull/68117 which now causes auth to fail with:

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://.../internal/security/login
```

which is a result of:

```
'{"statusCode":400,"error":"Bad Request","message":"[request body.providerType]: expected value of type [string] but got [undefined]"}'
```

The login data should be updated to:

```json
{
  "params": {
    "username": "kibana_username", 
    "password": "kibana_password"
    }, 
  "currentURL": "", 
  "providerType": "basic", 
  "providerName": "cloud-basic"
}
```

**To Reproduce**
1. attempt to auth against Kibana

### PR DESCRIPTION
**Pull request by brokensound77**
## Issues
resolves #403 

## Summary
To account for changes to the login data structure while still maintaining backwards compatibility for pre-7.10, the `connector` will first attempt the old structure and if the specific failure is detected, attempt the updated structure.

### CODE REVIEW

**Review by rw-access — APPROVED** [review]
thanks for maintaining backwards compat!
LGTM

**Comment by peasead** [comment]
Is this related?
```
python3 -m detection_rules kibana --cloud-id id:base64 -u user -p passphrase upload-rule rule.toml

█▀▀▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄▄▄ ▄   ▄      █▀▀▄ ▄  ▄ ▄   ▄▄▄ ▄▄▄
█  █ █▄▄  █  █▄▄ █    █   █  █ █ █▀▄ █      █▄▄▀ █  █ █   █▄▄ █▄▄
█▄▄▀ █▄▄  █  █▄▄ █▄▄  █  ▄█▄ █▄█ █ ▀▄█      █ ▀▄ █▄▄█ █▄▄ █▄▄ ▄▄█

Loading rules from rules
Loaded 1 rules
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "detection_rules/__main__.py", line 28, in <module>
    main()
  File "detection_rules/__main__.py", line 25, in main
    root(prog_name="detection_rules")
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "detection_rules/kbwrap.py", line 73, in upload_rule
    rules = RuleResource.bulk_create(api_payloads)
  File "detection-rules/kibana/resources.py", line 26, in bulk_create
    responses = Kibana.current().post(cls.BASE_URI + "/_bulk_create", data=resources)
  File "detection-rules/kibana/connector.py", line 151, in current
    raise RuntimeError("No Kibana connector in scope!")
RuntimeError: No Kibana connector in scope!
```

Kibana is 7.9.2 in ESS.

**Review by threat-punter — APPROVED** [review]

**Comment by brokensound77** [comment]
I have not seen that error @peasead. Do you still get that when running from this branch?

**Comment by peasead** [comment]
yeah, I just tried a `git pull` (to be sure) on `main`. Just had that again.

If it's just me and no one else is having issues with the `kibana` commandlet...it's just me.

**Comment by brokensound77** [comment]
you would need use this branch not main @peasead. I am going to merge this, then you can pull main and test (I have a feeling it may not be an actual issue but we can follow up directly)

**Pull request merged**
