### PR TITLE
[New Rule] Adding Data Exfiltration Rules from Advanced Analytic DED Package

### PR DESCRIPTION
**Pull request by ajosh0504**
## Summary
This PR moves the detection rules from the Data Exfiltration Detection [integration](https://github.com/elastic/integrations/tree/main/packages/ded/kibana/security_rule) package, into the detection-rules repo.

### CODE REVIEW

**Comment by terrancedejesus** [comment]
Added updated integrations manifests and schemas in recent commit. Should be good to go and merge.
Although DED has no fields available in integrations, there are no rules with queries which have unique fields so we are fine. Also, the integration manifests and schemas will have blank values by represent the integration versions as keys. This is important for building the `related_integrations` field.

**Comment by ajosh0504** [comment]
> Also, the integration manifests and schemas will have blank values by represent the integration versions as keys. This is important for building the related_integrations field.

@terrancedejesus anything I can help with here?

**Comment by terrancedejesus** [comment]
>@terrancedejesus anything I can help with here?
@ajosh0504 nope but thank you! We can merge this as soon as we have approvals.

**Review by terrancedejesus — APPROVED** [review]
Approving!

**Review by imays11 — APPROVED** [review]

**Pull request merged**
