### PR TITLE
Adding related integrations to ML rules

### PR DESCRIPTION
**Pull request by ajosh0504**
## Issues
#2963 

## Summary
This PR adds related integrations to ML rules.

### CODE REVIEW

**Comment by terrancedejesus** [comment]
@ajosh0504 - Made some adjustments to the logic. Following table shows the ML rule name, what integration tags were added in the metadata and then what was dynamically generated for the `related_integrations` field within the API rule object. Pushing commit soon.

| Rule Name                                                   | Defined Integrations                                   | Determined Integrations                                                                       |
|------------------------------------------------------------|--------------------------------------------------------|---------------------------------------------------------------------------------------------|
| Spike in AWS Error Messages                                | ['aws']                                                | [{'package': 'aws', 'integration': None}]                                                    |
| Rare AWS Error Code                                        | ['aws']                                                | [{'package': 'aws', 'integration': None}]                                                    |
| Unusual City For an AWS Command                            | ['aws']                                                | [{'package': 'aws', 'integration': None}]                                                    |
| Unusual Country For an AWS Command                         | ['aws']                                                | [{'package': 'aws', 'integration': None}]                                                    |
| Unusual AWS Command for a User                             | ['aws']                                                | [{'package': 'aws', 'integration': None}]                                                    |
| DNS Tunneling                                              | ['endpoint', 'network_traffic']                        | [{'package': 'endpoint', 'integration': None}, {'package': 'network_traffic', 'integration': None}] |
| Unusual DNS Activity                                       | ['endpoint', 'network_traffic']                        | [{'package': 'endpoint', 'integration': None}, {'package': 'network_traffic', 'integration': None}] |
| Unusual Web Request                                        | ['endpoint', 'network_traffic']                        | [{'package': 'endpoint', 'integration': None}, {'package': 'network_traffic', 'integration': None}] |
| Unusual Web User Agent                                     | ['endpoint', 'network_traffic']                        | [{'package': 'endpoint', 'integration': None}, {'package': 'network_traffic', 'integration': None}] |
| Spike in Failed Logon Events                               | ['auditd_manager', 'endpoint', 'system']               | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}, {'package': 'system', 'integration': None}] |
| Spike in Logon Events                                      | ['auditd_manager', 'endpoint', 'system']               | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}, {'package': 'system', 'integration': None}] |
| Spike in Successful Logon Events from a Source IP          | ['auditd_manager', 'endpoint', 'system']               | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}, {'package': 'system', 'integration': None}] |
| Unusual Linux Process Calling the Metadata Service         | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Unusual Linux User Calling the Metadata Service            | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Unusual Login Activity                                     | ['auditd_manager', 'endpoint', 'system']               | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}, {'package': 'system', 'integration': None}] |
| Unusual Windows Process Calling the Metadata Service       | ['endpoint', 'windows']                                | [{'package': 'endpoint', 'integration': None}, {'package': 'windows', 'integration': None}]   |
| Unusual Windows User Calling the Metadata Service          | ['endpoint', 'windows']                                | [{'package': 'endpoint', 'integration': None}, {'package': 'windows', 'integration': None}]   |
| Unusual Linux System Information Discovery Activity        | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Unusual Linux Network Configuration Discovery              | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Unusual Linux Network Connection Discovery                 | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Unusual Linux Process Discovery Activity                   | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Unusual Linux User Discovery Activity                      | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Suspicious Powershell Script                               | ['endpoint', 'windows']                                | [{'package': 'endpoint', 'integration': None}, {'package': 'windows', 'integration': None}]   |
| Unusual Hour for a User to Logon                           | ['auditd_manager', 'endpoint', 'system']               | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}, {'package': 'system', 'integration': None}] |
| Unusual Source IP for a User to Logon from                 | ['auditd_manager', 'endpoint', 'system']               | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}, {'package': 'system', 'integration': None}] |
| Rare User Logon                                            | ['auditd_manager', 'endpoint', 'system']               | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}, {'package': 'system', 'integration': None}] |
| Unusual Linux Username                                     | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Unusual Windows Username                                   | ['endpoint', 'windows']                                | [{'package': 'endpoint', 'integration': None}, {'package': 'windows', 'integration': None}]   |
| Unusual Windows Remote User                                | ['endpoint', 'windows']                                | [{'package': 'endpoint', 'integration': None}, {'package': 'windows', 'integration': None}]   |
| Spike in Firewall Denies                                   | ['endpoint', 'network_traffic']                        | [{'package': 'endpoint', 'integration': None}, {'package': 'network_traffic', 'integration': None}] |
| Spike in Network Traffic                                   | ['endpoint', 'network_traffic']                        | [{'package': 'endpoint', 'integration': None}, {'package': 'network_traffic', 'integration': None}] |
| Unusual Linux Network Activity                             | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Unusual Linux Network Port Activity                        | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Suspicious Linux Network Tool Discovery                    | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Anomalous Linux Process Creation                           | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Anomalous Linux Process Termination                        | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Anomalous Linux Network Activity                           | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Anomalous Windows Process Creation                         | ['endpoint', 'windows']                                | [{'package': 'endpoint', 'integration': None}, {'package': 'windows', 'integration': None}]   |
| Anomalous Windows Process Termination                      | ['endpoint', 'windows']                                | [{'package': 'endpoint', 'integration': None}, {'package': 'windows', 'integration': None}]   |
| Anomalous Windows Network Activity                         | ['endpoint', 'windows']                                | [{'package': 'endpoint', 'integration': None}, {'package': 'windows', 'integration': None}]   |
| Rare Anomalous Windows Process for a User                  | ['endpoint', 'windows']                                | [{'package': 'endpoint', 'integration': None}, {'package': 'windows', 'integration': None}]   |
| Rare Anomalous Linux Process for a User                    | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |
| Anomalous Linux Compiler Activity                          | ['auditd_manager', 'endpoint']                         | [{'package': 'auditd_manager', 'integration': None}, {'package': 'endpoint', 'integration': None}] |

**Comment by ajosh0504** [comment]
@terrancedejusus Thanks for your changes. I think saying `aws` is sufficient. We check for `cloudtrail` specifically in the datafeeds where needed and also I'm not really seeing a separate `cloudtrail` package [here](https://github.com/elastic/integrations/tree/main/packages)?

**Review by Mikaayenson — APPROVED** [review]
LGTM; Not sure what's up with the CLA (if @ajosh0504 has signed). May need to kick it with a nop commit.

**Review by w0rk3r — APPROVED** [review]
LGTM

**Comment by terrancedejesus** [comment]
@ajosh0504 thanks for the insight. Then I think this PR is good to go.

Regarding the packaging, your correct in that `cloudtrail` is not a root package, but it is defined as a separate integration and can be found in the [manifest](https://github.com/elastic/integrations/blob/73858fd862257d9f47e4c595fbec798244ab6483/packages/aws/manifest.yml#L99) of the `aws` package itself. What we do with rule validation and typically enforce that all queries have `event.dataset` where, for example, `aws.cloudtrail` is the `package.integration`. Then we check that `aws` is valid and we have the schemas, then we check if `cloudtrail` is in the policy templates of the manifest and is valid. When the rules are then converted to API format `related_integrations: {'package':'aws','integration':'cloudtrail', 'version':'1.0.2'}` is given and a URL link to that specific integration: `AWS CloudTrail`. Rather, with these rules it will point to the `AWS` integration, which users will then need to read the docs and know to rather install the service specific integration `AWS CloudTrail`.

**Comment by terrancedejesus** [comment]
@ajosh0504 - when you have time, could you add a nop commit to try and kick the CLA check as Mika mentioned?

**Pull request merged**
