### PR TITLE
[Rule Tuning] Clearing Windows Event Logs

### LINKED ISSUE #1381: [Rule Tuning] Clearing Windows Console History
**Proposed Rule Name Change**

Clearing Windows Event Logs and Console History

## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/windows/defense_evasion_clearing_windows_event_logs.toml

## Description

**Current Rule**

```
process where event.type in ("process_started", "start") and
  (process.name : "wevtutil.exe" or process.pe.original_file_name == "wevtutil.exe") and
    process.args : ("/e:false", "cl", "clear-log") or
  process.name : "powershell.exe" and process.args : "Clear-EventLog"
```

**Proposed Rule**

References Used:
- https://adamtheautomator.com/powershell-delete-file/
- https://community.sophos.com/sophos-labs/b/blog/posts/powershell-command-history-forensics

```
process where event.type in ("process_started", "start") and
  (process.name : "wevtutil.exe" or process.pe.original_file_name == "wevtutil.exe") and
    process.args : ("/e:false", "cl", "clear-log") or
  process.name : "powershell.exe" and process.args : ("Clear-EventLog","Remove-Item","*ConsoleHost*history*")
```

### PR DESCRIPTION
**Pull request by austinsonger**
## Issues

Resolves #1381

## Summary

- https://adamtheautomator.com/powershell-delete-file/
- https://community.sophos.com/sophos-labs/b/blog/posts/powershell-command-history-forensics

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by w0rk3r** [comment]
This one is better in a separated rule IMO, Command history logs are not exactly the same as Windows Event Logs, and you can also add the `Clear-History` cmdlet on it. [ref](https://attack.mitre.org/techniques/T1070/003/)

Wdyt @brokensound77 ?

**Comment by brokensound77** [comment]
> This one is better in a separated rule IMO, Command history logs are not exactly the same as Windows Event Logs, and you can also add the `Clear-History` cmdlet on it. [ref](https://attack.mitre.org/techniques/T1070/003/)
> 
> Wdyt @brokensound77 ?

That sounds like a good plan to me, thanks @w0rk3r. Does this work for you @austinsonger ?

**Comment by w0rk3r** [comment]
Closing this one in favor of an [New Rule] PR, feel free to reopen this one if you want to discuss it further. Thanks!

**Comment by austinsonger** [comment]
I was just going to change this into the new rule...

**Pull request closed without merging**
