### PR TITLE
fixing typo in 127.0.0.1 address

### PR DESCRIPTION
**Pull request by alwashali**
## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by Aegrah** [comment]
cc @w0rk3r

**Review by w0rk3r — APPROVED** [review]
LGTM, nice catch! Please sign https://www.elastic.co/contributor-agreement so we can proceed merging it

**Comment by alwashali** [comment]
I did sign the agreement

**Review by Aegrah — APPROVED** [review]
Thanks!

**Pull request merged**
