### PR TITLE
[New Rule] Microsoft 365 Exchange DKIM Signing Configuration Disabled

### LINKED ISSUE #465: [New Rule] O365 Exchange DKIM Signing Config Disabled
## Description
Identifies when a DomainKeys Identified Mail (DKIM) signing configuration is disabled in Office 365. With DKIM in Office 365, messages that are sent from Exchange Online will by cryptographically signed. This will allow the receiving email system to validate that the messages were generated by a server that the organization authorized and not being spoofed.

CIS Control:
7.8 Implement DMARC and Enable Receiver-Side Verification

## Required Info

- **Eventing Sources:**
`filebeat-*`

- **Platforms**
`o365`

- **Target ECS Version:** x.x.x
- **New fields required in ECS for this?**
- **Related issues or PRs**

## Optional Info
- **References:**
https://docs.microsoft.com/en-us/powershell/module/exchange/set-dkimsigningconfig?view=exchange-ps

## Example Logic
```
event.dataset:o365.audit and event.provider:Exchange and event.category:web and event.action:"Set-DkimSigningConfig" and o365.audit.Parameters.Enabled:False and event.outcome:success
```

## Screenshot

image

### PR DESCRIPTION
**Pull request by bm11100**
## Issues
resolves #465 

## Summary
Identifies when a DomainKeys Identified Mail (DKIM) signing configuration is disabled in Microsoft 365. With DKIM in Microsoft 365, messages that are sent from Exchange Online will be cryptographically signed. This will allow the receiving email system to validate that the messages were generated by a server that the organization authorized and not being spoofed.

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Review by Samirbous — APPROVED** [review]

**Comment by bm11100** [comment]
when #570 merges, the `non-ecs-schema` modification may no longer be needed. will confirm.

**Review by threat-punter — APPROVED** [review]
👍

**Comment by rw-access** [comment]
I updated half of the bug.
The other half is this:
https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/o365/audit/_meta/fields.yml#L194-L195

How do we want to handle this behavior for validation @brokensound77 and @bm11100?

**Comment by brokensound77** [comment]
> I updated half of the bug.
> The other half is this:
> https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/o365/audit/_meta/fields.yml#L194-L195
> 
> How do we want to handle this behavior for validation @brokensound77 and @bm11100?

What did Stucki say? Can we just leave it generic to accept any type whenever `object` is encountered. With that, we could always fall back to `non-ecs` if we needed to be explicit, which means we should give precedence to that

**Review by devonakerr — APPROVED** [review]

**Review by rw-access — APPROVED** [review]

**Pull request merged**
