### PR TITLE
[Rule Tuning] PowerShell Suspicious Discovery Related Windows API Functions

### PR DESCRIPTION
**Pull request by w0rk3r**
## Summary

Adds more discovery-related Windows API functions

### CODE REVIEW

**Review by imays11 — CHANGES_REQUESTED** [review]
Can you add the following techniques: 
[T1482 ](https://attack.mitre.org/techniques/T1482/) (ex: DsEnumerateDomainTrusts)
[T1087 ](https://attack.mitre.org/techniques/T1087/) (ex: NetWkstaUserEnum) 
[T1087.001](https://attack.mitre.org/techniques/T1087/001/) (ex: GetUserNameEx)

**Review by imays11 — COMMENTED** [review]
Are any of the following discovery related functions worth considering here as well? If not, I was planning to create a BBR rule for these.

``` 
NetUserEnum
NetUserGetInfo
NetGroupEnum
NetGroupGetInfo
NetGroupGetUsers
NetLocalGroupEnum
NetLocalGroupGetMembers
NetWkstaTransportEnum
NetServerGetInfo
NetShareEnum
NetUserModalsGet
NetScheduleJobEnum
```

**Review by Samirbous — APPROVED** [review]

**Comment by w0rk3r** [comment]
@imays11 nice review and suggestions, this one is ready for another round

**Review by imays11 — APPROVED** [review]
Looks good!

**Pull request merged**
