### PR TITLE
[Unusual File Creation ADS] Add Outlook.exe as a Query Exception

### LINKED ISSUE #2813: [Rule Tuning] Unusual File Creation - Alternate Data Stream
## Link to rule
[defense_evasion_unusual_ads_file_creation.toml](https://github.com/elastic/detection-rules/blob/main/rules/windows/defense_evasion_unusual_ads_file_creation.toml)

## Description
This rule already excludes some Microsoft apps such as `msedge.exe` and `explorer.exe`, but the rule also detects any time a user interacts with an attachment in Outlook. I feel the query for this rule should also exclude "outlook.exe".

### PR DESCRIPTION
**Pull request by MakoWish**
## Issues
- Closes #2813 

## Summary
This rule triggers with any interaction with attachments in Outlook. The PR adds `outlook.exe` as an exception to the query. 

## Contributor checklist

- [X] Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- [X] Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Review by w0rk3r — APPROVED** [review]

**Review by Aegrah — APPROVED** [review]

**Review by Samirbous — APPROVED** [review]
thanks LGTM

**Comment by MakoWish** [comment]
Pinging @DefSecSentinel, @terrancedejesus.

**Review by terrancedejesus — APPROVED** [review]
LGTM! Thanks for the adding this exception.

**Comment by MakoWish** [comment]
Anything else needed to get this merged?

**Pull request merged**
