### PR TITLE
[Rule Tuning] Update PowerShell script_block queries to avoid partial matches

### PR DESCRIPTION
**Pull request by w0rk3r**
## Summary

Update PowerShell queries to avoid partial matches (which are causing FPs) due to field type change (wildcard)

### CODE REVIEW

**Review by DefSecSentinel — APPROVED** [review]
LGTM

**Review by terrancedejesus — APPROVED** [review]
LGTM

**Comment by baserock** [comment]
Using 'quick query preview' over past month in rule creation.
    current psreflect rule: **200930 hits**
    with changes suggested in file changes psreflect rule: **51621 hits**

It appears that you overlooked the need for  Add-Win32Type to be "Add-Win32Type" too.
    With addition of "Add-Win32Type" to file changes psreflect rule: **0 hits**

_Note: we have this rule turned off due to lack of value provided so I am unable/unwilling to verify if ALL the hits are false positives._

**Review by brokensound77 — APPROVED** [review]

**Comment by w0rk3r** [comment]
Thanks a lot for confirming this @baserock, and nice catch on the missing one.

> we have this rule turned off due to lack of value provided so I am unable/unwilling to verify if ALL the hits are false positives.

If they are not shown after the change, they are. Thanks for bringing this to my attention, and if you have any other rules that are causing alert fatigue with FPs, feel free to ping me on Telegram (t.me/w0rk3r) or #security-detection-rules channel on [Elastic Community Slack](https://ela.st/slack).

**Pull request merged**
