### PR TITLE
[Rule Tuning] Add endgame support for Windows Rules

### LINKED ISSUE #2037: Review Windows rules for Endgame compatibility
## Description

Review rules for Endgame compatibility and add index. 

- Create an endgame stack for testing purposes.
- Check datasets and make sure our rule query aligns.
- Check the fields in the query to make sure the field is available in the endgame event.
- Document differences between the Endgame dataset and Endpoint dataset if any appear. 

cc @DefSecSentinel @Samirbous @w0rk3r @shashank-elastic

### PR DESCRIPTION
**Pull request by w0rk3r**
## Issues

Resolves #2037 

## Summary

Adds support for endgame EDR to Windows detection Rules. Each rule has a screenshot of the query matching the intended event on Endgame, as well as the event attached in a gist.

## Alert Data

<details>
<summary>Deleting Backup Catalogs with Wbadmin</summary>

image

[Event Data](https://gist.github.com/w0rk3r/23a2b9665923e33c769aa1fd0c076196)

</details>

<details>
<summary>Modification of Boot Configuration</summary>

image

[Event Data](https://gist.github.com/w0rk3r/d649de3c6a22b887a6566f8425ca9b51)

</details>

<details>
<summary>High Number of Process and/or Service Terminations</summary>

image

[Event Data](https://gist.github.com/w0rk3r/151f9d67b4be781e938488449e17ef65)

</details>

<details>
<summary>Volume Shadow Copy Deleted or Resized via VssAdmin</summary>

image

[Event Data](https://gist.github.com/w0rk3r/4f9d1c4b0abe785ad78c325d9abb174c)

</details>

<details>
<summary>Volume Shadow Copy Deletion via PowerShell</summary>

image

[Event Data](https://gist.github.com/w0rk3r/bff422715aa9781645b470783a01b597)

</details>

<details>
<summary>Volume Shadow Copy Deletion via WMIC</summary>

image

[Event Data](https://gist.github.com/w0rk3r/9bab7450c990bff1b57f962298f64dc2)

</details>

<details>
<summary>Windows Script Executing PowerShell</summary>

image

[Event Data](https://gist.github.com/w0rk3r/7c00b7bc0277d49700afa69e29b88fda)

</details>

<details>
<summary>Windows Script Interpreter Executing Process via WMI</summary>

image

[Event Data](https://gist.github.com/w0rk3r/2412d6680cb5160f04a43d96fa9b63c3)

</details>

<details>
<summary>Microsoft Exchange Server UM Writing Suspicious Files</summary>

image

[Event Data](https://gist.github.com/w0rk3r/dfe85e9bb024a9a258ea961dc849422c)

</details>

<details>
<summary>Microsoft Exchange Server UM Spawning Suspicious Processes</summary>

image

[Event Data](https://gist.github.com/w0rk3r/db5ba4b5a25c227cd91ecde508e2f245)

</details>

<details>
<summary>Microsoft Exchange Worker Spawning Suspicious Processes</summary>

image

[Event Data](https://gist.github.com/w0rk3r/4eb793ac01cee9d8cc7c076ee2351c40)

</details>

<details>
<summary>Suspicious MS Office Child Process</summary>

image

[Event Data](https://gist.github.com/w0rk3r/1c50d4b09f7aa1bdf4eb99f418a3e2f0)

</details>

<details>
<summary>Suspicious MS Outlook Child Process</summary>

image

[Event Data](https://gist.github.com/w0rk3r/9759b8b57d6d48df878c978410b7bdfe)

</details>

<details>
<summary>Unusual Child Process of dns.exe</summary>

image

[Event Data](https://gist.github.com/w0rk3r/63ddfc679a2364dc15c9c8186fea9f24)

</details>

<details>
<summary>Unusual File Modification by dns.exe</summary>

image

[Event Data](https://gist.github.com/w0rk3r/ac5b0a019b357af803cbf4b3e3699372)

</details>

<details>
<summary>Suspicious Explorer Child Process</summary>

image

[Event Data](https://gist.github.com/w0rk3r/da72917634132bf7769552c76c38c158)

</details>

<details>
<summary>NullSessionPipe Registry Modification</summary>

image

[Event Data](https://gist.github.com/w0rk3r/3d0f8538984159c1e85d6e5d9997cac7)

</details>

<details>
<summary>Potential Remote Desktop Shadowing Activity</summary>

image

[Event Data](https://gist.github.com/w0rk3r/b37fc09186d9d08383f4696aa03877f6)

</details>

<details>
<summary>Mounting Hidden or WebDav Remote Shares</summary>

image

[Event Data](https://gist.github.com/w0rk3r/e8445949e4ac748199e9fee2ad751be2)

</details>

<details>
<summary>RDP Enabled via Registry</summary>

image

[Event Data](https://gist.github.com/w0rk3r/12dafc0a905f741fb8c94ceb0fecc165)

</details>

<details>
<summary>Remote File Copy to a Hidden Share</summary>

image

[Event Data](https://gist.github.com/w0rk3r/d3bc222d1d7b78583957e509fcd02c82)

</details>

<details>
<summary>Service Control Spawned via Script Interpreter</summary>

image

[Event Data](https://gist.github.com/w0rk3r/4a2a381cf1e38e0b474e3caa9ecd9836)

</details>

<details>
<summary>Suspicious RDP ActiveX Client Loaded</summary>

image

[Event Data](https://gist.github.com/w0rk3r/2fd729c3ae17a4aa37e400f9efd627ca)

</details>

<details>
<summary>Lateral Movement via Startup Folder</summary>

image

[Event Data](https://gist.github.com/w0rk3r/522a3a4ac696f193180d405aea650168)

</details>

<details>
<summary>Registry Persistence via AppCert DLL</summary>

image

[Event Data](https://gist.github.com/w0rk3r/caec3775fe14557aae242c2b19a3a64b)

</details>

<details>
<summary>Registry Persistence via AppInit DLL</summary>

image

[Event Data](https://gist.github.com/w0rk3r/fb9caa7ce5efa29edfba3b27c3605658)

</details>

<details>
<summary>Image File Execution Options Injection</summary>

image

[Event Data](https://gist.github.com/w0rk3r/83f9bf157f3ebb5d7c4fac2e06278808)

</details>

<details>
<summary>Suspicious Startup Shell Folder Modification</summary>

image

[Event Data](https://gist.github.com/w0rk3r/abf382b2b16377612a7ed75baa6b258f)

</details>

<details>
<summary>Persistence via Scheduled Job Creation</summary>

image

[Event Data](https://gist.github.com/w0rk3r/c052100f46c2e2ccd8d464fac3fcd8df)

</details>

<details>
<summary>Persistence via Microsoft Office AddIns</summary>

image

[Event Data](https://gist.github.com/w0rk3r/9291e19279de45720c7e9d6bad19931f)

</details>

<details>
<summary>Persistence via Microsoft Outlook VBA</summary>

image

[Event Data](https://gist.github.com/w0rk3r/3c9755d3da4729d2e77d63397e6db02b)

</details>

<details>
<summary>New ActiveSyncAllowedDeviceID Added via PowerShell</summary>

image

[Event Data](https://gist.github.com/w0rk3r/ecad2f4624197ae90c9f04c23bda08b5)

</details>

<details>
<summary>Startup or Run Key Registry Modification</summary>

image

[Event Data](https://gist.github.com/w0rk3r/dcd609eac0e0b9c0b0c3181b1adf14fd)

</details>

<details>
<summary>Execution of Persistent Suspicious Program</summary>

image

[Event Data](https://gist.github.com/w0rk3r/7f14fbb37d16f51bcb18099714847ade)

</details>

<details>
<summary>Unusual Persistence via Services Registry</summary>

image

[Event Data](https://gist.github.com/w0rk3r/f83cd88671bd1e20bb1a665dd45a6329)

</details>

<details>
<summary>Startup Persistence by a Suspicious Process</summary>

image

[Event Data](https://gist.github.com/w0rk3r/fa94342f695d1161678ac2184e9c9126)

</details>

<details>
<summary>Persistent Scripts in the Startup Directory</summary>

image

[Event Data](https://gist.github.com/w0rk3r/c92a4f9eebc7e37e351a9dce8846650d)

</details>

<details>
<summary>Component Object Model Hijacking</summary>

image

[Event Data](https://gist.github.com/w0rk3r/bebb708bba9e83693a676cdeb141a892)

</details>

<details>
<summary>Suspicious Image Load (taskschd.dll) from MS Office</summary>

image

[Event Data](https://gist.github.com/w0rk3r/a59e3eccd507e9127ac1e6c77de5f086)

</details>

<details>
<summary>Suspicious ImagePath Service Creation</summary>

image

[Event Data](https://gist.github.com/w0rk3r/63b688d2152cb5ce83357920c2736410)

</details>

<details>
<summary>System Shells via Services</summary>

image

[Event Data](https://gist.github.com/w0rk3r/e77ae2f67dba977766b7115b40949c3e)

</details>

<details>
<summary>Persistence via BITS Job Notify Cmdline</summary>

image

[Event Data](https://gist.github.com/w0rk3r/ae10060da43d4e1d6b80f3e40608ac30)

</details>

<details>
<summary>Installation of Security Support Provider</summary>

image

[Event Data](https://gist.github.com/w0rk3r/fd3ebd4c2e0a6151c804e273b857e48e)

</details>

<details>
<summary>Persistence via TelemetryController Scheduled Task Hijack</summary>

image

[Event Data](https://gist.github.com/w0rk3r/039520d10a92213762ed3b3f8b048865)

</details>

<details>
<summary>Persistence via WMI Event Subscription</summary>

image

[Event Data](https://gist.github.com/w0rk3r/974880de58482c3f4588dbea46a87f1c)

</details>

<details>
<summary>Web Shell Detection: Script Process Child of Common Web Processes</summary>

image

[Event Data](https://gist.github.com/w0rk3r/fb16d2c5334939c255363c244b1e2fad)

</details>

<details>
<summary>Disabling User Account Control via Registry Modification</summary>

image

[Event Data](https://gist.github.com/w0rk3r/4dd7ecf585c0ce57ee3c275ed0030c2c)

</details>

<details>
<summary>Potential LSA Authentication Package Abuse</summary>

image

[Event Data](https://gist.github.com/w0rk3r/6311e84e15fdc72330a0e514df349a35)

</details>

<details>
<summary>Privilege Escalation via Named Pipe Impersonation</summary>

image

[Event Data](https://gist.github.com/w0rk3r/92e2d04cd6f5a61b2c527cece869ab3e)

</details>

<details>
<summary>Suspicious DLL Loaded for Persistence or Privilege Escalation</summary>

image

[Event Data](https://gist.github.com/w0rk3r/fe8502eed12e9a473184934c25a1a7b8)

</details>

<details>
<summary>Potential Port Monitor or Print Processor Registration Abuse</summary>

image

[Event Data](https://gist.github.com/w0rk3r/07dc6b56ac30d8ab9204d16072619905)

</details>

<details>
<summary>Suspicious Print Spooler Point and Print DLL</summary>

image

[Event Data](https://gist.github.com/w0rk3r/3ebd80036fe4d007fbc5aa2dee5acc7c)

</details>

<details>
<summary>Suspicious PrintSpooler Service Executable File Creation</summary>

image

[Event Data](https://gist.github.com/w0rk3r/71f51acdd4702777ae18ac0d88645762)

</details>

<details>
<summary>Suspicious Print Spooler File Deletion</summary>

image

[Event Data](https://gist.github.com/w0rk3r/b01383dd34f529887277f08a41fb7683)

</details>

<details>
<summary>Suspicious Print Spooler SPL File Created</summary>

image

[Event Data](https://gist.github.com/w0rk3r/1e61876736c9e8db38b92508141061ee)

</details>

<details>
<summary>Privilege Escalation via Windir Environment Variable</summary>

image

[Event Data](https://gist.github.com/w0rk3r/72f08e5601ace6e54681ddde537446b8)

</details>

<details>
<summary>UAC Bypass Attempt with IEditionUpgradeManager Elevated COM Interface</summary>

image

[Event Data](https://gist.github.com/w0rk3r/364b1c1ab228da40b2364c17cfb5ffbb)

</details>

<details>
<summary>UAC Bypass via ICMLuaUtil Elevated COM Interface</summary>

image

[Event Data](https://gist.github.com/w0rk3r/02e8b96ed76be00b9b6910bbd5fb5b07)

</details>

<details>
<summary>UAC Bypass via DiskCleanup Scheduled Task Hijack</summary>

image

[Event Data](https://gist.github.com/w0rk3r/e7e44b10f437575363f5a2c60a53df42)

</details>

<details>
<summary>Bypass UAC via Event Viewer</summary>

image

[Event Data](https://gist.github.com/w0rk3r/56084ffd352eb3f5b87f2dc986fdef52)

</details>

<details>
<summary>UAC Bypass Attempt via Windows Directory Masquerading</summary>

image

[Event Data](https://gist.github.com/w0rk3r/19413837ea040fe062cb7587e7069d69)

</details>

<details>
<summary>UAC Bypass via Windows Firewall Snap-In Hijack</summary>

image

[Event Data](https://gist.github.com/w0rk3r/e7dd737bba8f50423e820a4fd3662650)

</details>

<details>
<summary>Unusual Parent-Child Relationship</summary>

image

[Event Data](https://gist.github.com/w0rk3r/c95921f2900dcd4b684fb3d7c8cfac90)

</details>

<details>
<summary>Unusual Service Host Child Process - Childless Service</summary>

image

[Event Data](https://gist.github.com/w0rk3r/d2d3c5a88ff56e98de874582796a6bac)

</details>

Rules I didn't simulate, but I assume they'd work based on the fields used:

* Remote Execution via File Shares
* Adobe Hijack Persistence
* Creation of a Hidden Local User Account
* Creation or Modification of a new GPO Scheduled Task or Service
* Scheduled Task Created by a Windows Script
* Potential Modification of Accessibility Binaries
* Persistence via Hidden Run Key Detected
* Persistence via Update Orchestrator Service Hijack
* Persistence via WMI Standard Registry Provider
* UAC Bypass Attempt via Elevated COM Internet Explorer Add-On Installer
* UAC Bypass Attempt via Privileged IFileOperation COM Interface

### CODE REVIEW

**Review by Mikaayenson — COMMENTED** [review]
Just want to confirm a couple things.
- Do you mean to add the RTAs?
- Are we intentionally adding the Endgame variations of the data? 
 
LGTM otherwise, less the conflicts, which I think we decided to hold on resolving until the integrations PR is in.

**Comment by w0rk3r** [comment]
@Mikaayenson, yup, I'd have some draft RTAs for these. And yeah, some intentional modifications to make the logic work on the endgame data.

>I think we decided to hold on resolving until the integrations PR is in.

Conflicts resolved. The one we are going to hold is the Linux one

**Review by terrancedejesus — APPROVED** [review]
LGTM.

**Review by Mikaayenson — COMMENTED** [review]
Some of these are missing an `updated_date` change and some updated dates say December. Should we bump these all to February?

**Review by Mikaayenson — APPROVED** [review]

**Pull request merged**
