### PR TITLE
[FR] Update Release Workflow Token Naming

### PR DESCRIPTION
**Pull request by eric-forte-elastic**
## Summary

This PR updates the name of the token used for our release workflow.

### CODE REVIEW

**Review by shashank-elastic — APPROVED** [review]
We have an ongoing release. Can we wait for the merge.
Not that it will break things, we dont want to add delta to release flow during an ongoing release. 

Approving for a delayed merge.

**Comment by eric-forte-elastic** [comment]
> We have an ongoing release. Can we wait for the merge. Not that it will break things, we dont want to add delta to release flow during an ongoing release.
> 
> Approving for a delayed merge.

Agreed, no issue at all waiting until after the release from my perspective :+1:

**Comment by Mikaayenson** [comment]
After the release, can you test before merging by going to the manual workflow and switching to this branch? Then if the PRs are opened successfully, you can just close them or @shashank-elastic you can release from this branch to test during the release, and it it fails just release from main.

**Review by Mikaayenson — APPROVED** [review]

**Comment by Mikaayenson** [comment]
> There is an error @eric-forte-elastic image
> 
> https://github.com/elastic/detection-rules/actions/runs/9714232012/job/26812826177

Then @eric-forte-elastic you can revert it for the security-docs workflow for now. @shashank-elastic you can reach out to those folks who manage the token and ask to extend permissions to security-docs and open a 2nd pr.

**Comment by shashank-elastic** [comment]
> > There is an error @eric-forte-elastic image
> > https://github.com/elastic/detection-rules/actions/runs/9714232012/job/26812826177
> 
> Then @eric-forte-elastic you can revert it for the security-docs workflow for now. @shashank-elastic you can reach out to those folks who manage the token and ask to extend permissions to security-docs and open a 2nd pr.

Am uncertain how this will fly. the machine token is shared across all teams of sec-intel like TDS and others. Why are not maintaining our own system tokens, given that we have a release fleet automation ourselves.

Having said that happy to initiate a request to extend permissions.

**Comment by shashank-elastic** [comment]
Also looking at the original PR for release-docs automation [refer](https://github.com/elastic/detection-rules/pull/2745/files). We had 2 sets of tokens `Protections Machine` and `READ_WRITE_RELEASE_FLEET`. The `READ_WRITE_RELEASE_FLEET` was used to check out secuirty-docs and the `Protections Machine` to raise a PR.

So in purpose `Protections Machine` has permissions to raise the PR to security-docs repo. We just need to fall back to our `READ_WRITE_RELEASE_FLEET` for checking out the  repo is what i feel. Am also surprised to see 2 sets of keys used in the operation in original PR, which makes me feel there was a strong reason for it be intented like this
cc @Mikaayenson @eric-forte-elastic

**Review by terrancedejesus — APPROVED** [review]

**Pull request closed without merging**
