### PR TITLE
[Rule Tuning] Administrator role assigned to an okta user

### LINKED ISSUE #1159: [Rule Tuning] Administrator Role Assigned to an Okta User
## Link to rule
https://github.com/elastic/detection-rules/blob/main/rules/okta/persistence_administrator_role_assigned_to_okta_user.toml

## Description

- This rule is missing the time when a user is added to a group that have administrative-like privileges.
  - Adding `user added to group membership`
 
-  There are multiple types of Administrator privileges such
      -  "Super Administrator" which is `debugContext.debugData.privilegeGranted`

```
event.dataset:okta.system and event.action:user.account.privilege.grant or debugContext.debugData.privilegeGranted or
group.user_membership.add
```

### PR DESCRIPTION
**Pull request by austinsonger**
## Summary

Resolves #1159 

- This rule is missing the time when a user is added to a group that have administrative-like privileges.
  - Adding `user added to group membership`
  - This could be a separate rule, but I don't see any reason to, and it would make more sense to just combine it into this one.
 
-  There are multiple types of Administrator privileges such
      -  "Super Administrator" which is `debugContext.debugData.privilegeGranted`

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by threat-punter** [comment]
@austinsonger - I believe that `event.action:group.user_membership.add` is logged when an Okta user is added to any group included the `Everyone` default group, which is why I didn't include this event type in the rule.

**Comment by austinsonger** [comment]
@threat-punter Yeah you are correct so I modified it.

```
event.dataset:okta.system and event.action:user.account.privilege.grant or 
okta.debug_context.debug_data.threat_suspected:debugContext.debugData.privilegeGranted
```

**Comment by threat-punter** [comment]
@austinsonger by any chance, do you have an example event where `okta.debug_context.debug_data.threat_suspected:debugContext.debugData.privilegeGranted` is logged?

**Comment by austinsonger** [comment]
> @austinsonger by any chance, do you have an example event where `okta.debug_context.debug_data.threat_suspected:debugContext.debugData.privilegeGranted` is logged?

I will get an example this week.

**Comment by threat-punter** [comment]
@austinsonger did you get a chance to get an example event for this one? Cheers 👍

**Comment by austinsonger** [comment]
> @austinsonger did you get a chance to get an example event for this one? Cheers 👍

I'm going get an example this weekend, been a busy week.

**Comment by threat-punter** [comment]
No rush. I'll keep it open

**Comment by austinsonger** [comment]
> No rush. I'll keep it open

I'm doing some testing today on this.

**Comment by austinsonger** [comment]
I'm having some problems getting this to trigger. I'm going to close this for now and revisit this when i get this to trigger.

**Pull request closed without merging**
