### PR TITLE
[Rule Tuning] Add Filebeat and Auditbeat to Network Rules

### LINKED ISSUE #35: [Rule Tuning] Add auditbeat to network rules
## Description
The `auditbeat-*` Index needs to be added to network SIEM rules. 

Related to #14

### PR DESCRIPTION
**Pull request by peasead**
## Issues
Resolves #35

## Summary
This adds the Auditbeat and Filebeat indices to all of the Network rules.
```
from = "now-9m"
index = ["auditbeat-*", "filebeat-*", "packetbeat-*", "logs-endpoint.events.*"]
```

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Review by brokensound77 — APPROVED** [review]
Changes look good to me, so long as all these fields exist in auditbeat.

If you can bump the `updated_date` on these, then 👍

**Review by brokensound77 — COMMENTED** [review]
ahh, this was the missing tags error
```
AssertionError: cf53f532-9cc9-445a-9ae7-fced307ec53c - Cobalt Strike Command and Control Beacon -> Missing tags:
E               Actual tags: Elastic, Network, Threat Detection, Command and Control
E               Missing any of: Windows, macOS, Linux, Windows, macOS, Linux, Host
```

If you just add `Host` to these rules, then it will be resolved. May seem silly, but it is consistent with all the other rules since the data could be derived from endpoints

**Comment by peasead** [comment]
Gotcha. I saw that was the tag error, but as it was a network rule, I wasn't sure if it was an error in the unit test logic or something missing from the rule. 

I'll make those changes and update the PR next week.

**Comment by peasead** [comment]
I added `Host` and the `test` passed.

**Review by bm11100 — APPROVED** [review]
bump updated_date and LGTM

**Pull request merged**
