### PR TITLE
[WMI Incoming Lateral Movement] Modify Existing Query Exception

### LINKED ISSUE #2841: [Rule Tuning] WMI Incoming Lateral Movement
## Link to rule
[lateral_movement_incoming_wmi.toml](https://github.com/elastic/detection-rules/blob/main/rules/windows/lateral_movement_incoming_wmi.toml)

## Description
There is an existing exception in the query where process.args is:

`C:\\Windows\\CCM\\SystemTemp\\*`

Unfortunately, we have received some events where that same argument is single-quoted and is preceded with an ampersand:

`& 'C:\WINDOWS\CCM\SystemTemp\9b69a355-c98b-40c9-b315-1d9ba1542251.ps1'`

The preceding ampersand and single quote caused this event to trigger a detection when it is already expected to be ignore. 

## Example Data
```
{
  "is_partial": false,
  "is_running": false,
  "took": 20237,
  "timed_out": false,
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "sequences": [
      {
        "join_keys": [
          "646e7e77-6bef-4ba0-a25e-bcfb7b723f51"
        ],
        "events": [
          {
            "_index": ".ds-logs-endpoint.events.network-default-2023.03.10-000001",
            "_id": "S1UZbogBpkWDu5S6L3TC",
            "_source": {
              "agent": {
                "id": "98765432-fd70-4aaf-ac27-123456789abc",
                "type": "endpoint",
                "version": "8.6.2"
              },
              "process": {
                "Ext": {
                  "ancestry": [
                    "MGQ0ZWYyNjgtZmQ3MC00YWFmLWFjMjctZDA5YjE5ZTAyMzk1LTY4OC0xNjg1NDYwMzY1LjIxMTg2NDAwMA==",
                    "MGQ0ZWYyNjgtZmQ3MC00YWFmLWFjMjctZDA5YjE5ZTAyMzk1LTEwMTYtMTY4NTQ2MDM2NS45MDMzNzYwMA=="
                  ],
                  "code_signature": [
                    {
                      "trusted": true,
                      "subject_name": "Microsoft Windows Publisher",
                      "exists": true,
                      "status": "trusted"
                    }
                  ]
                },
                "code_signature": {
                  "trusted": true,
                  "subject_name": "Microsoft Windows Publisher",
                  "exists": true,
                  "status": "trusted"
                },
                "name": "svchost.exe",
                "pid": 2148,
                "entity_id": "MGQ0ZWYyNjgtZmQ3MC00YWFmLWFjMjctZDA5YjE5ZTAyMzk1LTIxNDgtMTY4NTQ2MDM2Ni45MTYxMjc2MDA=",
                "executable": """C:\Windows\System32\svchost.exe"""
              },
              "destination": {
                "address": "10.10.10.10",
                "port": 49666,
                "bytes": 314820,
                "ip": "10.10.10.10"
              },
              "source": {
                "address": "10.10.10.20",
                "port": 63256,
                "bytes": 5934,
                "ip": "10.10.10.20"
              },
              "message": "Endpoint network event",
              "network": {
                "bytes": 320754,
                "transport": "tcp",
                "type": "ipv4",
                "direction": "ingress"
              },
              "@timestamp": "2023-05-30T19:18:23.7594604Z",
              "ecs": {
                "version": "1.11.0"
              },
              "related": {
                "hosts": [
                  "Computer1"
                ],
                "ip": [
                  "10.10.10.10",
                  "10.10.10.20"
                ],
                "user": [
                  "local service"
                ]
              },
              "data_stream": {
                "namespace": "default",
                "type": "logs",
                "dataset": "endpoint.events.network"
              },
              "elastic": {
                "agent": {
                  "id": "98765432-fd70-4aaf-ac27-123456789abc"
                }
              },
              "host": {
                "hostname": "Computer1",
                "os": {
                  "Ext": {
                    "variant": "Windows 10 Enterprise"
                  },
                  "kernel": "22H2 (10.0.19045.2965)",
                  "name": "Windows",
                  "family": "windows",
                  "type": "windows",
                  "version": "22H2 (10.0.19045.2965)",
                  "platform": "windows",
                  "full": "Windows 10 Enterprise 22H2 (10.0.19045.2965)"
                },
                "ip": [
                  "10.10.10.12"
                ],
                "name": "Computer1",
                "id": "646e7e77-6bef-4ba0-a25e-bcfb7b723f51",
                "mac": [
                  "01:23:45:67:89:ab",
                ],
                "architecture": "x86_64"
              },
              "event": {
                "agent_id_status": "verified",
                "sequence": 249444,
                "ingested": "2023-05-30T19:18:44Z",
                "created": "2023-05-30T19:18:23.7594604Z",
                "kind": "event",
                "module": "endpoint",
                "action": "disconnect_received",
                "id": "N5MJbsy7A5/0Fxvb++++0dGL",
                "category": [
                  "network"
                ],
                "type": [
                  "end"
                ],
                "dataset": "endpoint.events.network"
              },
              "user": {
                "domain": "NT AUTHORITY",
                "name": "local service",
                "id": "S-1-5-19"
              }
            }
          },
          {
            "_index": ".ds-logs-endpoint.events.process-default-2023.03.10-000001",
            "_id": "h1UZbogBpkWDu5S6L3TC",
            "_source": {
              "agent": {
                "id": "98765432-fd70-4aaf-ac27-123456789abc",
                "type": "endpoint",
                "version": "8.6.2"
              },
              "process": {
                "Ext": {
                  "ancestry": [
                    "MGQ0ZWYyNjgtZmQ3MC00YWFmLWFjMjctZDA5YjE5ZTAyMzk1LTI2NzY4LTE2ODU0NzQzMDUuMjYzMjMxOTAw",
                    "MGQ0ZWYyNjgtZmQ3MC00YWFmLWFjMjctZDA5YjE5ZTAyMzk1LTExMjQtMTY4NTQ2MDM2NS41NDM1MDk3MDA=",
                    "MGQ0ZWYyNjgtZmQ3MC00YWFmLWFjMjctZDA5YjE5ZTAyMzk1LTY4OC0xNjg1NDYwMzY1LjIxMTg2NDAwMA==",
                    "MGQ0ZWYyNjgtZmQ3MC00YWFmLWFjMjctZDA5YjE5ZTAyMzk1LTEwMTYtMTY4NTQ2MDM2NS45MDMzNzYwMA=="
                  ],
                  "code_signature": [
                    {
                      "trusted": true,
                      "subject_name": "Microsoft Windows",
                      "exists": true,
                      "status": "trusted"
                    }
                  ],
                  "session_info": {
                    "authentication_package": "Negotiate",
                    "relative_logon_time": 13940.2303094,
                    "id": 0
                  },
                  "relative_file_creation_time": 1129148.3284181,
                  "authentication_id": "0x3e7",
                  "relative_file_name_modify_time": 1129148.3139206,
                  "token": {
                    "integrity_level_name": "system",
                    "security_attributes": [
                      "TSA://ProcUnique"
                    ],
                    "elevation_level": "default"
                  }
                },
                "parent": {
                  "args": [
                    """C:\WINDOWS\system32\wbem\wmiprvse.exe""",
                    "-Embedding"
                  ],
                  "name": "WmiPrvSE.exe",
                  "pid": 26768,
                  "args_count": 2,
                  "thread": {
                    "Ext": {
                      "call_stack_contains_unbacked": false
                    }
                  },
                  "entity_id": "MGQ0ZWYyNjgtZmQ3MC00YWFmLWFjMjctZDA5YjE5ZTAyMzk1LTI2NzY4LTE2ODU0NzQzMDUuMjYzMjMxOTAw",
                  "command_line": """C:\WINDOWS\system32\wbem\wmiprvse.exe -Embedding""",
                  "executable": """C:\Windows\System32\wbem\WmiPrvSE.exe"""
                },
                "pid": 2864,
                "working_directory": """C:\WINDOWS\system32\""",
                "entity_id": "MGQ0ZWYyNjgtZmQ3MC00YWFmLWFjMjctZDA5YjE5ZTAyMzk1LTI4NjQtMTY4NTQ3NDMwNS41NDY1NzAwMDA=",
                "executable": """C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe""",
                "args": [
                  """C:\WINDOWS\system32\WindowsPowerShell\v1.0\PowerShell.exe""",
                  "-NoLogo",
                  "-Noninteractive",
                  "-NoProfile",
                  "-ExecutionPolicy",
                  "Bypass",
                  """& 'C:\WINDOWS\CCM\SystemTemp\9b69a355-c98b-40c9-b315-1d9ba1542251.ps1'"""
                ],
                "code_signature": {
                  "trusted": true,
                  "subject_name": "Microsoft Windows",
                  "exists": true,
                  "status": "trusted"
                },
                "pe": {
                  "imphash": "88cb9a420410bda787e305b65518a934",
                  "original_file_name": "PowerShell.EXE"
                },
                "name": "powershell.exe",
                "args_count": 7,
                "command_line": "\"C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\PowerShell.exe\" -NoLogo -Noninteractive -NoProfile  -ExecutionPolicy Bypass \"& 'C:\\WINDOWS\\CCM\\SystemTemp\\9b69a355-c98b-40c9-b315-1d9ba1542251.ps1'\"",
                "hash": {
                  "sha1": "eb39e26a364ecd0691a59fcef61a90334112617e",
                  "sha256": "b4e7bc24bf3f5c3da2eb6e9ec5ec10f90099defa91b820f2f3fc70dd9e4785c4",
                  "md5": "bcf01e61144d6d6325650134823198b8"
                }
              },
              "@timestamp": "2023-05-30T19:18:25.54657Z",
              "ecs": {
                "version": "1.11.0"
              },
              "related": {
                "hosts": [
                  "Computer1"
                ],
                "ip": [
                  "10.10.10.12"
                ],
                "user": [
                  "system"
                ],
                "hash": [
                  "BCF01E61144D6D6325650134823198B8",
                  "EB39E26A364ECD0691A59FCEF61A90334112617E",
                  "B4E7BC24BF3F5C3DA2EB6E9EC5EC10F90099DEFA91B820F2F3FC70DD9E4785C4"
                ],
                "mac": [
                  "01:23:45:67:89:ab",
                ]
              },
              "data_stream": {
                "namespace": "default",
                "type": "logs",
                "dataset": "endpoint.events.process"
              },
              "elastic": {
                "agent": {
                  "id": "98765432-fd70-4aaf-ac27-123456789abc"
                }
              },
              "host": {
                "hostname": "Computer1",
                "os": {
                  "Ext": {
                    "variant": "Windows 10 Enterprise"
                  },
                  "kernel": "22H2 (10.0.19045.2965)",
                  "name": "Windows",
                  "family": "windows",
                  "type": "windows",
                  "version": "22H2 (10.0.19045.2965)",
                  "platform": "windows",
                  "full": "Windows 10 Enterprise 22H2 (10.0.19045.2965)"
                },
                "ip": [
                  "10.10.10.12"
                ],
                "name": "Computer1",
                "id": "646e7e77-6bef-4ba0-a25e-bcfb7b723f51",
                "mac": [
                  "01:23:45:67:89:ab",
                ],
                "architecture": "x86_64"
              },
              "event": {
                "agent_id_status": "verified",
                "sequence": 249555,
                "ingested": "2023-05-30T19:18:44Z",
                "created": "2023-05-30T19:18:25.54657Z",
                "kind": "event",
                "module": "endpoint",
                "action": "start",
                "id": "N5MJbsy7A5/0Fxvb++++0dNR",
                "category": [
                  "process"
                ],
                "type": [
                  "start"
                ],
                "dataset": "endpoint.events.process"
              },
              "message": "Endpoint process event",
              "user": {
                "domain": "NT AUTHORITY",
                "name": "system",
                "id": "S-1-5-18"
              }
            }
          }
        ]
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by MakoWish**
## Issues
- Closes #2841 

## Summary
There is an existing exception in the query where process.args is:

`C:\\Windows\\CCM\\SystemTemp\\*`

Unfortunately, we have received some events where that same argument is single-quoted and is preceded with an ampersand:

`& 'C:\WINDOWS\CCM\SystemTemp\9b69a355-c98b-40c9-b315-1d9ba1542251.ps1'`

The preceding ampersand and single quote caused this event to trigger a detection when it is already expected to be ignored. 

SCCM also utilizes a `ccmrepair.exe` process that should in included in the query. 

This PR adds a wildcard to the existing exclusion to include events with the prepended ampersand and single quote, as well as excepts the `ccmrepair.exe` process. 

## Contributor checklist

- [X] Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- [X] Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by MakoWish** [comment]
Pinging @w0rk3r

**Comment by MakoWish** [comment]
Pinging @terrancedejesus @w0rk3r

**Review by w0rk3r — APPROVED** [review]
LGTM, just need to bump updated_date

**Comment by MakoWish** [comment]
Bumped

**Review by imays11 — APPROVED** [review]
Looks good!

**Comment by MakoWish** [comment]
I can't merge, so would appreciate if someone could.

**Pull request merged**
