### PR TITLE
[Rule tuning] Fix evasion for disable iptables rule

### LINKED ISSUE #4: [Rule tuning] disable iptables rule can be bypassed
## Description

i noticed that the rule regarding the deactivation of iptables service is lacking a case when `systemctl` is being used to stop `iptables` instead of `firewalld`, as shown here: https://support.rackspace.com/how-to/use-iptables-with-centos-7/

https://github.com/elastic/detection-rules/blob/e48a987ce474c0e9795524bcb504b556946ad0ac/rules/linux/defense_evasion_attempt_to_disable_iptables_or_firewall.toml#L24

## Example Data

the command not being captured by current rules is:

```bash
systemctl (stop|kill|disable) iptables(6)
```

Edit (by  @rw-access): switched to issue template and updated title

### PR DESCRIPTION
**Pull request by phra**
will fix #4 

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
yes
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?
yes

### CODE REVIEW

**Comment by phra** [comment]
FYI I've signed the CLA just before opening the PR.. maybe the CLA bot is not updated yet. :smiley:

**Comment by rw-access** [comment]
I'm not 100% sure how the CLA bot works -- it already knows my GitHub account as an Elastic employee, so I'm kinda exempt. But doesn't hurt to double check the email/github user name you associated with it. And you can check your profile settings to make sure the account is linked: https://github.com/settings/emails

**Comment by phra** [comment]
@rw-access yep, I've inserted the correct GitHub username and email.

**Comment by rw-access** [comment]
Great! I'm less familiar with these commands, so I added a few reviewers that are more familiar with the review and the particular linux commands to double check the logic

**Comment by phra** [comment]
@brokensound77 done!

**Comment by phra** [comment]
:clinking_glasses:

**Pull request merged**
