### PR TITLE
[Rule Fix] PowerShell Kerberos Ticket Request

### PR DESCRIPTION
**Pull request by dan21san**
# Pull Request

*Issue link(s)*:

## Summary - What I changed

Rule link: /rules/windows/credential_access_posh_request_ticket.toml

I suggest to add a simple wildcard (**\***) before the string `*KerberosRequestorSecurityToken` .
Using the current query with the logs Im analysing, the string in question is not detected. While adding the wildcard does. 

However, the change also complies with the references in the rule and would not cause any missmatch with the current detection query.

Here Empire script screenshot 
image

Here my log screenshot 
image

## Checklist

- [ ] Added a label for the type of pr: `bug`, `enhancement`, `schema`, `Rule: New`, `Rule: Deprecation`, `Rule: Tuning`, `Hunt: New`, or `Hunt: Tuning` so guidelines can be generated
- [ ] Added the `meta:rapid-merge` label if planning to merge within 24 hours
- [ ] Secret and sensitive material has been managed correctly
- [ ] Automated testing was updated or added to match the most common scenarios
- [ ] Documentation and comments were added for features that require explanation

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Comment by protectionsmachine** [comment]
## Rule: Tuning - Guidelines

These guidelines serve as a reminder set of considerations when tuning an existing rule.

### Documentation and Context

- [ ] Detailed description of the suggested changes.
- [ ] Provide example JSON data or screenshots.
- [ ] Provide evidence of reducing benign events mistakenly identified as threats (False Positives).
- [ ] Provide evidence of enhancing detection of true threats that were previously missed (False Negatives).
- [ ] Provide evidence of optimizing resource consumption and execution time of detection rules (Performance).
- [ ] Provide evidence of specific environment factors influencing customized rule tuning (Contextual Tuning).
- [ ] Provide evidence of improvements made by modifying sensitivity by changing alert triggering thresholds (Threshold Adjustments).
- [ ] Provide evidence of refining rules to better detect deviations from typical behavior (Behavioral Tuning).
- [ ] Provide evidence of improvements of adjusting rules based on time-based patterns (Temporal Tuning).
- [ ] Provide reasoning of adjusting priority or severity levels of alerts (Severity Tuning).
- [ ] Provide evidence of improving quality integrity of our data used by detection rules (Data Quality).
- [ ] Ensure the tuning includes necessary updates to the release documentation and versioning.

### Rule Metadata Checks

- [ ] `updated_date` matches the date of tuning PR merged.
- [ ] `min_stack_version` should support the widest stack versions.
- [ ] `name` and `description` should be descriptive and not include typos.
- [ ] `query` should be inclusive, not overly exclusive. Review to ensure the original intent of the rule is maintained.

### Testing and Validation

- [ ] Validate that the tuned rule's performance is satisfactory and does not negatively impact the stack.
- [ ] Ensure that the tuned rule has a low false positive rate.

**Comment by w0rk3r** [comment]
> Using the current query with the logs Im analysing, the string in question is not detected. While adding the wildcard does.

Hey @dan21san, can you give more details on how you're testing this?

Due to the field type, we don't need `*` to do partial keyword matches:

image

**Comment by dan21san** [comment]
Hi @w0rk3r thank you for the very quick reply .

My mistake, I had not checked whether the type of the field in question was actually correct with the integration documentation. 
In my case it is a `keyword` type :( so the problem lies in the ingest pipeline on our side . 

I will investigate whether it is remapped somewhere.

**Comment by w0rk3r** [comment]
@dan21san Ouch! As this is a local issue, I'll close the PR

**Pull request closed without merging**
