### PR TITLE
[Rule Tuning] added rule name override for cloud_defend integration rule

### PR DESCRIPTION
**Pull request by mitodrummer**
## Summary
The cloud-defend service now sends a "message" field which will be used to give our alerts more detail.

## Target release
8.8

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? y
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)? y

### CODE REVIEW

**Review by terrancedejesus — APPROVED** [review]

**Comment by terrancedejesus** [comment]
@mitodrummer can you update the the `updated_date` field in the metadata by chance? After this I think we are good to merge.

**Review by imays11 — APPROVED** [review]
Updated the date and approved👍🏾

**Comment by mitodrummer** [comment]
can this be merged?

**Comment by terrancedejesus** [comment]
> can this be merged?

@mitodrummer go for it!

**Comment by mitodrummer** [comment]
> > can this be merged?
> 
> @mitodrummer go for it!

I don't seem to have the power to merge on this repo :)

**Pull request merged**
