### PR TITLE
[FR] Remove `required_fields` and `related_integrations` from Rule SHA256 Contents

### PR DESCRIPTION
**Pull request by terrancedejesus**
## Issues
* https://github.com/elastic/detection-rules/issues/2894

## Summary
This PR removes `related_integrations` and `required_fields` from the hashable contents of a rule regarding the SHA256 generation. These fields are build time fields whose values rely on data that is external to Detection Rules or not deterministic by rule authors. Thus consistently cause version issues. Please review the issue for more details.

## Additional Information
The biggest consideration here is that since these details will not be added to the SHA256 calculation, they may change but rule versions will not and thus Kibana will not update them.

* `required_fields` - Since these are parsed directly from the query, then the query would ultimately change and thus so would the SHA256. The reason we are removing these is because there is potential to be a difference in required fields `type` depending on the ECS, beats or integration schemas across stack versions. If not found, the `type` is `unknown` but then if found at a later schema version would, for example be `keyword`.
* `related_integrations` - This relies on the integration manifests and schemas which could change at any release. The related integration version given could diverge across stack versions due to, for example, a breaking change which has resulted in us min-stacking the rule as a result because the dynamically determined version differs across stacks and thus so does the rule version. While this will not require a rule update if this changes, it always points to the min compatible value. Thus @spong has opened an issue to always point to the latest, regardless of version.

### CODE REVIEW

**Review by eric-forte-elastic — APPROVED** [review]
Manual review, LGTM :+1: 

And great write up from: https://github.com/elastic/detection-rules/issues/2894

**Review by Mikaayenson — APPROVED** [review]

**Comment by terrancedejesus** [comment]
#### Update - 06/10/2023
Discussed with DED team. Takeaway notes below.

- We may not want to excluded these fields from the SHA256.
- We should look to add the forward dev packages to `stack-schema-map.yml` to be more aligned
- We should add `non-ecs-schema.json` to the `required_fields` check. If a field is not found, then it is not available in any schema and thus ultimately the query has fields that are potentially non-existent.
- We should add `integrations-schema` checks for `required_fields` as well as it does not check these and thus may introduce the same issue in the future.

**Review by brokensound77 — CHANGES_REQUESTED** [review]
https://github.com/elastic/detection-rules/pull/2896#issuecomment-1629838634

**Comment by terrancedejesus** [comment]
@Mikaayenson we may be able to close. Last I recall, we decided not to do this after all.

**Pull request closed without merging**
