### PR TITLE
[Rule Tuning] Update Google Workspace rules to remove compatibility with deprecated gsuite integration

### LINKED ISSUE #1705: [Rule Tuning] Remove Gsuite.* fields from google workspace rules
## Description

As the gsuite integration schema removed all backward compatibility with the gsuite fields, our ruleset needs to be updated to remove those fields and dataset references and define a `min_stack_version`.

### PR DESCRIPTION
**Pull request by w0rk3r**
## Issues

Resolves #1705 

## Summary

Adjust rules to remove compatibility with the deprecated gsuite module

### CODE REVIEW

**Review by Samirbous — APPROVED** [review]

**Review by brokensound77 — APPROVED** [review]
LGTM, Thanks!

**Comment by jmikell821** [comment]
@brokensound77 @w0rk3r looks like there was 23 changed files and this PR has only 10 changed files, so I'll have to do a cross comparison to see what was missed. Also the change from `current` to `{branch}` is important. Example:
`- https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-gsuite.html`
to
` - https://www.elastic.co/guide/en/beats/filebeat/{branch}/filebeat-module-google_workspace.html`

**Comment by brokensound77** [comment]
I think this is an unrelated (but overlapping of some rules) change @jmikell821. I would imagine all of the google rules need to be update. (cc:@jrodewig)

**Review by jrodewig — COMMENTED** [review]
Post-merge LGTM.

**Comment by w0rk3r** [comment]
@jmikell821 / @jrodewig, is there any additional change that we should do and is not covered by this PR?

**Pull request merged**
