### PR TITLE
[Rule tuning] existing hpining and strace activity rule.

### PR DESCRIPTION
**Pull request by shashank-elastic**
## Issues
#2027 

## Summary

1. For Rule 1 in consideration already MITRE details have been added as part of https://github.com/elastic/detection-rules/pull/2012. This issue tracks the following changes in the description and query changes from KQL to EQL.
-- This won't be done as it was rejected in review for having no impact. 
2. For Rule 2 in consideration, the issue tracks MITRE details, and description changes.

## Contributor checklist

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/detection-rules/blob/main/CONTRIBUTING.md)?

### CODE REVIEW

**Review by brokensound77 — COMMENTED** [review]
Why would these need to be converted to EQL rules?

**Review by w0rk3r — CHANGES_REQUESTED** [review]
++, if we are not using sequences here, the type conversion is not needed

**Comment by shashank-elastic** [comment]
@brokensound77 --> The PR contains MITRE details addition along with query changes, we can revert the query alone and keep the PR open to judge the other aspects.!

**Review by Mikaayenson — APPROVED** [review]
LGTM

**Review by imays11 — APPROVED** [review]
Looks good!

**Pull request merged**
