### PR TITLE
[Rule Tuning] Remove unreleased timeline from alert correlation rules

### PR DESCRIPTION
**Pull request by w0rk3r**
## Issues

#2456 

## Summary

Remove the timeline references from alert correlation rules

### CODE REVIEW

**Review by terrancedejesus — APPROVED** [review]
LGTM. Timeline IDs and templates are removed. Rules should backport to 8.3 which is the earliest stack version these rules exist.

**Comment by terrancedejesus** [comment]
@w0rk3r while the timeline templates may not be available, is there any additional logic we may want to add to the existing rule or maybe investigation guide that would at least steer the analyst in the right direction?

**Review by Mikaayenson — APPROVED** [review]
Plan is to address this issue now and readdress the rule without timelines later.

**Comment by w0rk3r** [comment]
Merging this one without timelines or additional investigation guide as will default to an effective threshold timeline

**Pull request merged**
